#+STARTUP: oddeven
#+PROPERTY: header-args:emacs-lisp :tangle init.el

* Firstfirst
:PROPERTIES:
:ID:       bd4a3fcf-1669-40b8-a1c1-d9adf07fd947
:END:

** Copyright

Copyright (c) 2015-2017 Marco Wahl <marcowahlsoft@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

** Compile the Config File
:PROPERTIES:
:ID:       c2c181f3-e02e-4754-b1ef-0798bcd61eda
:END:

Call =org-babel-tangle= on this Org file to get file =init.el=.

Follow the link to do the call

[[elisp:(org-babel-tangle)][(org-babel-tangle)]]

or use key sequence =C-cv t=.

** First Line
:PROPERTIES:
:ID:       2a5b2368-a53b-478a-a59a-ecaf4edfbcc3
:END:

#+begin_src emacs-lisp
;;; init.el --- personal emacs config file marco wahl -*- lexical-binding: t ; eval: (read-only-mode 1)-*-
#+end_src

Set to read-only to make edits harder.  Recall that the tangled file
is not supposed to be edited.

** Conform to el-Tradition
:PROPERTIES:
:ID:       50b27b8e-ef4e-4b89-a810-90c7c56bb665
:END:

The following lines are traditionally in every elisp file.  These
lines also please checkdoc, the elisp documentation checker.

#+begin_src emacs-lisp

;;; Commentary:

;; THIS FILE HAS BEEN GENERATED.


;;; Code:
#+end_src

** Debugging
:PROPERTIES:
:ID:       7cb42826-a8c0-49be-b880-e5c5edad2023
:END:

Switch on debugging, in case.

#+BEGIN_SRC emacs-lisp
;; (setq debug-on-error t)
#+END_SRC

** Customize
:PROPERTIES:
:ID:       f572690d-b639-4b28-a58c-3d5fe1eab821
:END:

Early load of the custom.el to avoid irritating overridings from
custom-el.

Emacs allows to specify the storage-location of customization done via
the emacs-customize interface.  The default is to keep the
customization in the init-file.

Take care about overrides due to customizations.

#+BEGIN_SRC emacs-lisp

(setq custom-file "~/.emacs.d/init/.emacs-custom.el")
(load custom-file)
#+END_SRC

[2017-02-10 Fri 09:23] the override with the small letters did not work.

#+BEGIN_SRC emacs-lisp

(setq org-structure-template-alist
      '(("s" "#+begin_src ?\n\n#+end_src")
        ("e" "#+begin_example\n?\n#+end_example")
        ("q" "#+begin_quote\n?\n#+end_quote")
        ("v" "#+begin_verse\n?\n#+end_verse")
        ("V" "#+begin_verbatim\n?\n#+end_verbatim")
        ("c" "#+begin_center\n?\n#+end_center")
        ("l" "#+begin_latex\n?\n#+end_latex")
        ("L" "#+latex: ")
        ("h" "#+begin_html\n?\n#+end_html")
        ("H" "#+html: ")
        ("a" "#+begin_ascii\n?\n#+end_ascii")
        ("A" "#+ascii: ")
        ("i" "#+index: ?")
        ("I" "#+include: %file ?")
        ("n" "#+name: ?")
        ("t" "*************** ?\n*************** end")))
#+END_SRC

* Config
:PROPERTIES:
:ID:       c4fc8c97-a9d8-4228-a4e7-8bc97138a68f
:END:

#+begin_src emacs-lisp
;(load-file "init-config.el")
(setq shr-external-browser 'browse-url-firefox)
#+end_src

** Workarounds
:PROPERTIES:
:ID:       a592b13a-4e61-40d5-a391-f67614fcb544
:END:

The following might help to keep this file going.  Ideally this
section does not exist.

#+BEGIN_SRC emacs-lisp
;; (defun ert--activate-font-lock-keywords ()
;;   ;; [2016-04-16 Sat 14:40] wtf?  startup breaks.
;;   ;; some change with emacs?  function missing?
;;   )
(require 'ert)
#+END_SRC

- [2017-05-19 Fri] still needed.

** Don't load outdated byte code
:PROPERTIES:
:ID:       8fa15afd-71c1-44f3-bdca-2e547bd9f603
:END:

#+BEGIN_SRC emacs-lisp
(setq load-prefer-newer t)
#+END_SRC

Found the above in lunaryorn's config at
https://github.com/lunaryorn/.emacs.d/blob/master/init.el
[2015-05-18 Mon 21:56].

** Frame Config
:PROPERTIES:
:ID:       576a103f-c461-4f83-bb13-12187141d810
:END:

[2016-02-05 Fri 22:53] Try out minibuffer in extra frame.

This has something!  Unfortunately I'm not 100% content.  Maybe
I need to exercise more.

#+BEGIN_SRC emacs-lisp
;; (setq initial-frame-alist '((minibuffer . nil)))
;; (setq default-frame-alist '((minibuffer . nil)))
#+END_SRC

** Speed Keys For Org Files
:PROPERTIES:
:ID:       bb85cbf0-0ad9-40a3-a770-0d9c1a53281f
:END:

#+BEGIN_SRC emacs-lisp

(defun mw-org-up ()
  (interactive)
  (let ((start-level (funcall outline-level)))
    (if (<= start-level 1)
        (goto-char (point-min))
      (org-speed-move-safe (quote outline-up-heading)))))

(add-hook
 ; [2016-11-04 Fri 10:40] 'org-mode-hook
 'org-load-hook
 (lambda ()
   (setq org-speed-commands-user
         '(("K" . org-cut-subtree)
           ("-" . mw-org-hide-meta-info-lines)
           ("+" . mw-org-show-meta-info-lines)
           ("*" . (lambda (&optional arg)
                    (interactive "P")
                    (avy-goto-char-2 ?* 32 arg)))
           ;; ("." . mw-avy-goto-char) ; somehow this conflicts with auctex
           ("." . (lambda () (interactive)
                    (org-narrow-to-subtree)
                    (let ((avy-all-windows nil)) (call-interactively #'avy-goto-char))))
           ("9" . org-decrypt-entry)
           (";" . org-timer-set-timer)
           ("G" . ace-link)
           ("H" . org-rise)
           ("J" . org-clock-goto)
           ("N" org-speed-move-safe 'outline-next-visible-heading)
           ("P" org-speed-move-safe 'outline-previous-visible-heading)
           ("4" . org-display-org-properties)
           ("S" . (lambda (arg) (interactive "P")
                    (mw-org-narrow-to-one-level-above)
                    (unless arg
                      (org-mark-ring-push)
                      (mw-org-up)
                      (org-orgee-as-top-level-tree-establish))))
           ("T" . org-tree-to-indirect-buffer)
           ("W" . (lambda () (interactive)
                    (org-orgee-as-top-level-tree-unravel)
                    (widen)))
           ("Y" . org-agenda)
           ("`" . mw-org-up)
           ("d" . org-attach)
           ("k" . org-capture)
           ("m" . org-teleport)
           ("q" . org-columns-quit)
           ("s" . (lambda (&optional arg)
                    (interactive "P")
                    (org-narrow-to-subtree)
                    (unless arg
                      (org-orgee-as-top-level-tree-establish))))
           ("x" . (lambda (arg) "Org export of orgee." (interactive "P")
                    (let ((org-export-initial-scope 'subtree))
                      (org-export-dispatch))))
           ("y" . org-property-action)
           ("z" . org-add-note)
           ("h" . org-refile-dwim)
           ))
   ;; (add-to-list 'org-speed-commands-user (cons ","  #'avy-goto-line))
   ;; (add-to-list 'org-speed-commands-user (cons "S" #'mw-org-narrow-to-one-level-above))
   ))
#+END_SRC

** Org from Source
:PROPERTIES:
:ID:       15ae3b79-0786-41d0-b7d4-1933d4b75c5b
:END:

#+BEGIN_SRC emacs-lisp
(let ((orgmodelocation (expand-file-name "~/p/org/org-mode")))
  (push (concat orgmodelocation "/lisp") load-path)
  (push (concat orgmodelocation "/contrib/lisp") load-path)
  (eval-after-load "org-agenda"
    '(progn
       (org-defkey org-agenda-mode-map (kbd "Y") #'org-agenda)
       ;; (org-defkey org-agenda-mode-map (kbd "C-,") #'ignore) ; wtf is this line?
       ))
  (eval-after-load 'info
    '(progn (info-initialize)
  	    (add-to-list
	     'Info-directory-list
	     (concat (expand-file-name "~/p/org/org-mode") ; orgmodelocation
		     "/doc"))))
  (eval-after-load 'eww
    '(progn (org-link-set-parameters "eww" :follow #'eww :store #'org-eww-store-link))))

(require 'org)
#+END_SRC

** Package Resources
:PROPERTIES:
:ID:       baff0889-3d65-48fa-a31e-b96c40012ea2
:END:

The gnu package repo is not included from the start.

#+BEGIN_SRC emacs-lisp
(setf package-archives nil)
(add-to-list 'package-archives '("mw" . "/home/b/p/elisp/mw/packs/") t)
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
;; (add-to-list 'package-archives '("RSW-Packages" . "http://www.plasmas.biz/rswe/") t)
#+END_SRC

[2016-02-08 Mon 12:57] Possibly drop usage of the custom file
entirely for more clarity in the init process.

** Package Initialization
:PROPERTIES:
:ID:       13572b22-efe5-4f24-80b3-abac8ca26245
:END:

#+BEGIN_SRC emacs-lisp
(package-initialize)
#+END_SRC

'(package-initialize)' gets added automatically according to
help:package-initialize.  But maybe too late.

** use-package
:PROPERTIES:
:ID:       e86f38d0-7910-4dcd-81d5-edf553e55e6d
:END:

=use-package= allows convenient emacs package configuration.

#+BEGIN_SRC emacs-lisp
(require 'use-package)
#+END_SRC

* Packages

** In use
*** elm-mode

#+BEGIN_SRC emacs-lisp
(use-package elm-mode  :ensure t)
#+END_SRC

**** elm-mode from local clone

#+BEGIN_SRC emacs-lisp
;; (add-to-list 'load-path "~/p/elisp/external/elm-mode")
;; (require 'elm-mode)
#+END_SRC

*** async
:PROPERTIES:
:ID:       df37af31-8c32-4004-92c8-8f9d2f12f150
:END:

#+BEGIN_SRC emacs-lisp
(use-package async :config (dired-async-mode 1))
#+END_SRC

*** camcorder
:PROPERTIES:
:ID:       75d25b4e-7872-40ba-b87e-f1719803cbbd
:END:

#+BEGIN_SRC emacs-lisp
(use-package camcorder
  :config (setf camcorder-output-directory "~/media/screencasts/camcorder"))
#+END_SRC

*** ace-link
:PROPERTIES:
:ID:       54e121e0-f32a-45e9-a3db-efa7e2cb5980
:END:

Quickly follow links in certain modes e.g. info-mode.

#+BEGIN_SRC emacs-lisp
(use-package ace-link
  :config (ace-link-setup-default))
#+END_SRC

**** TODO Check for integration with ert and more                  :noexport:

[2016-05-03 Tue 09:01] Read about this on the project page.
*** evil-numbers
:PROPERTIES:
:ID:       7ea0fc4b-dbdb-4b40-88f5-2ab1eafb3d00
:END:

Quickly add to integers in buffer with prefix-arguments for
adding/subtracting that value.  Default is 1.

#+BEGIN_SRC emacs-lisp
(use-package evil-numbers
  :bind
  ("M-+" . evil-numbers/inc-at-pt)
  ("M--" . evil-numbers/dec-at-pt))
#+END_SRC

**** TODO Check Similar Packages                                   :noexport:

There are more packages in this field.

*** chronos
:PROPERTIES:
:ID:       b5728916-4338-40ca-8f9f-a945d98267d4
:END:

~chronos~ allows to conveniently set timers and say a text when the
timer is done.

#+BEGIN_SRC emacs-lisp
(use-package chronos
  :config (setf chronos-text-to-speech-program "espeak"
                chronos-text-to-speech-program-parameters "-s 111"
                chronos-expiry-functions
                '(chronos-buffer-notify
                  chronos-text-to-speech-notify
                  (lambda (c)
                    (browse-url-firefox
                     "https://www.youtube.com/watch?v=32FB-gYr49Y")))))
#+END_SRC

*** swiper
:PROPERTIES:
:ID:       51429cfc-a12a-4cda-826c-5d59dc6c2c65
:END:

#+BEGIN_SRC emacs-lisp
(use-package swiper
  :bind ("C-S-s" . swiper))
#+END_SRC

*** dired-narrow
:PROPERTIES:
:ID:       5579337d-b273-4cdd-b211-9ba702055dbf
:END:

At very first invocation do ~M-x dired-narrow~ in a dired buffer.
After that the key binding is active.

Recall g for getting rid of all filtering.

#+BEGIN_SRC emacs-lisp
(use-package dired-narrow
  :ensure t)
#+END_SRC

*** stumpwm-mode
:PROPERTIES:
:ID:       e0f2ee47-0ce8-4f48-9ff0-d6de1363ec8e
:END:

Stumpish integration.

#+BEGIN_SRC emacs-lisp
(use-package stumpwm-mode
  :config (setq stumpwm-shell-program
                (expand-file-name "~/.stumpwm.d/modules/util/stumpish/stumpish")))
#+END_SRC

*** keyfreq
:PROPERTIES:
:ID:       a6cb2d15-2bd8-4db1-a39e-033789041e75
:END:

From the documentation at https://github.com/dacap/keyfreq:

#+BEGIN_QUOTE
...use keyfreq-show to see how many times you used a command.
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(use-package keyfreq
  :config (progn (keyfreq-mode 1)
                 (keyfreq-autosave-mode 1)))
#+END_SRC

*** wrap-region
:PROPERTIES:
:ID:       429b4d6c-0c11-4f4b-b43a-2540809b772a
:END:

Press a key to decorate region .

#+BEGIN_SRC emacs-lisp
(use-package wrap-region
  :ensure t
  :config (progn
            (wrap-region-global-mode t)
            (wrap-region-add-wrapper "`" "'")
            (wrap-region-add-wrapper "~" "~" nil 'org-mode)
            (wrap-region-add-wrapper "*" "*" nil 'org-mode)
            (wrap-region-add-wrapper "_" "_" nil 'org-mode)
            (wrap-region-add-wrapper "=" "=" nil 'org-mode)
            (wrap-region-add-wrapper ":" ":" nil 'org-mode)
            (wrap-region-add-wrapper "#+begin_quote\n" "\n#+end_quote" "q" 'org-mode)
            (wrap-region-add-wrapper "#+begin_example\n" "\n#+end_example" "e" 'org-mode)
            (wrap-region-add-wrapper "#+begin_verse\n" "\n#+end_verse" "v" 'org-mode)
            (wrap-region-add-wrapper "#+begin_src \n" "\n#+end_src" "s" 'org-mode)))
#+END_SRC
*** auth-password-store
:PROPERTIES:
:ID:       f3cd686b-49bb-404f-9e7a-e13df534b5ca
:END:

[2016-11-03 Thu 10:50] i suspect this to interfer with the
gnus-gmail connection.

auth-stuff -> pass(word-store)

#+BEGIN_SRC emacs-lisp
;; (use-package auth-password-store
;;   :ensure t
;;   :config (auth-pass-enable))
#+END_SRC

*** avy
:PROPERTIES:
:ID:       72c5f7a8-60b1-494e-ace6-69b608b3f674
:END:

Move cursor onto a visible character.

=avy= is similar to ace-jump-mode.  I read that avy is the variant
that gets maintained.

#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  :bind ( ;; ("C-." . mw-avy-goto-char) ; somehow this conflicts with auctex (see also other appearances)
         ("C-." . avy-goto-char)
         ("C->" . avy-goto-char-in-line)
         ("C-," . avy-goto-line))
  :config
  (setq avy-keys
                '(?e ?t ?h ?u ?n ?o ?s ?a ?d ?i ?-
                     ?. ?c ?, ?r ?l ?' ?p ?y ?f ?g
                     ?m ?j ?b ?k ?w ?q ?v ?x ?z))
  ;; (setf avy-all-windows nil)
  (setf avy-all-windows-alt t) ; hint: behavior prefix arg
  (avy-setup-default)
  ;; [2016-05-03 Tue 15:56]: was
  ;;(eval-after-load "isearch" '(define-key isearch-mode-map (kbd "C-'") 'avy-isearch))
  )
#+END_SRC

*** avy-zap
:PROPERTIES:
:ID:       c0bfb12b-f9fc-4597-8736-492fc536ef06
:END:

A replacement of zap-to-char.

#+BEGIN_SRC emacs-lisp
(use-package avy-zap
  :bind (("M-z" . avy-zap-to-char-dwim)
         ("M-Z" . avy-zap-up-to-char-dwim)))
#+END_SRC

*** on-screen
:PROPERTIES:
:ID:       2c8a926f-d92f-4824-846d-cfc85689e24a
:END:

Adds a visual symbol about the previous page after scrolling a page.
This might help sometimes.  Try together with rope-read.

#+BEGIN_SRC emacs-lisp
(use-package on-screen
  :ensure t
  :config (global-on-screen-mode))
#+END_SRC

*** page-break-lines
:PROPERTIES:
:ID:       1b9e0af1-1669-4b6e-bfcf-846f550f7c59
:END:

Display page breaks nicely.  Similar to [[id:5e169d24-bc68-42da-ae9d-2f3d190a9547][form-feed-mode]].

#+BEGIN_SRC emacs-lisp
(use-package page-break-lines)
#+END_SRC

*** form-feed-mode
:PROPERTIES:
:ID:       5e169d24-bc68-42da-ae9d-2f3d190a9547
:END:

Display page breaks nicely.  Similar to [[id:1b9e0af1-1669-4b6e-bfcf-846f550f7c59][page-break-lines]].

#+BEGIN_SRC emacs-lisp
(use-package form-feed)
#+END_SRC

*** browse-kill-ring
:PROPERTIES:
:ID:       20de8639-3711-45ef-aa5e-8fcd31703369
:END:

Activate any time with M-x browse-kill-ring or with M-y but the
latter only if _not_ immediately after yank.

#+BEGIN_SRC emacs-lisp
(use-package browse-kill-ring
  :config
  (browse-kill-ring-default-keybindings)) ; M-y
#+END_SRC

*** expand-region
:PROPERTIES:
:ID:       196f772e-5a6f-4e19-8b6f-81a38cb0c9a6
:END:

=expand-region= often expands the region to what i mean.

#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :config
  (global-set-key (kbd "C-=") #'er/expand-region))
#+END_SRC

*** ido-hacks
:PROPERTIES:
:ID:       66bdba19-c2bf-4c68-b30d-493af73c92e7
:END:

ido-hacks sits on top of ido and makes ido even cooler.  When
ido-hacks-mode comes into the way then just switch it off.

#+BEGIN_SRC emacs-lisp
(use-package ido-hacks
  :init (ido-mode)
  :config (ido-hacks-mode))
#+END_SRC

*** lentic
:PROPERTIES:
:ID:       0fe5c819-7945-47f3-9c85-8c146405547d
:END:

Activattion of lentic as proposed in lentics documentation lentic.el.

#+BEGIN_SRC emacs-lisp
(use-package lentic
  :config (global-lentic-mode))
#+END_SRC

*** magit
:PROPERTIES:
:ID:       4016460d-1156-49df-8811-d1667d057292
:END:

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :config (define-key magit-file-section-map "C" 'magit-commit-add-log) ;; "C" also on filename-lines
 )
#+END_SRC

*** company mode
:PROPERTIES:
:ID:       09620e2a-f12e-4b6a-bd06-68312c1b5264
:END:

#+BEGIN_SRC emacs-lisp
(use-package company
  :config (global-company-mode))
#+END_SRC

*** key chord
:PROPERTIES:
:ID:       653ed90b-c5ff-415a-bbc9-ead0527da736
:END:

#+BEGIN_SRC emacs-lisp
(use-package key-chord
  :config
  (key-chord-mode 1) ;; recall: e.g. (key-chord-unset-global "bb") for undef a key-chord.
  (key-chord-define-global "w1" #'reverse-words)
  (key-chord-define-global "v3" (lambda () (interactive) (mw-org-hide-meta-info-lines)))
  (key-chord-define-global "v4" (lambda () (interactive) (mw-org-show-meta-info-lines)))
  (key-chord-define-global "v1" #'emms-volume-lower)
  (key-chord-define-global "v2" #'emms-volume-raise)
  (key-chord-define-global "7g" #'mw-split-window-horizontally-at-point)
  (key-chord-define-global "4p" #'mw-split-window-vertically-at-point)
  (key-chord-define-global "x6" (lambda () (interactive)
                                  (dotimes (_ 2)
                                    (mw-rotate-split))))
  (key-chord-define-global "r7" #'mw-org-refile-set-direct-target-bm)
  (key-chord-define-global "r8" #'mw-org-refile-refile-to-direct-target)
  (key-chord-define-global "r1" #'mw-carry-region-toggle)
  (key-chord-define-global "l1" #'mw-mark-line)
  (key-chord-define-global "o6" #'org-open-at-point-global)
  (key-chord-define-global "c4" #'recompile)
  (key-chord-define-global "o8" #'ace-link)
  (key-chord-define-global "s-" #'beacon-blink) ; locate the cursor easily
  (key-chord-define-global "ao" #'other-window)
  (key-chord-define-global ";q" #'other-frame)
  (key-chord-define-global "qj" #'mw-exchange-to-buddy)
  (key-chord-define-global ".," #'next-buffer)
  (key-chord-define-global "><"       ; this is S-., on dovorak layout
                           #'previous-buffer)
  (key-chord-define-global "r9" #'rope-read-mode)
  (key-chord-define-global "yy" #'mw-duplicate-line)
  (key-chord-define-global "''" #'mw-umlautify-before-point)
  (key-chord-define-global "'," #'mw-umlautify-before-point)
  (key-chord-define-global "uu" (lambda (&optional in-place)
                                  (interactive "P")
                                  (if in-place (mw-translate-in-place-eng+deu)
                                    (mw-translate-as-message-eng+deu))))
  (key-chord-define-global "hh" (lambda () (interactive) (recenter 0))) ; #'recenter-top-bottom; afair H is a respecive vim binding?
  (key-chord-define-global "``" #'mw-alternate-up)
  (key-chord-define-global "~~" #'dired-jump)
  (key-chord-define-global ",," #'lentic-mode-move-lentic-window)
  (key-chord-define-global "3." #'delete-other-windows)
  (key-chord-define-global "c8" #'delete-window) ; for kinesis keyboard
  (key-chord-define-global "g8" #'delete-window) ; for cherry keyboard
  (key-chord-define-global "m1" #'magit-status)
  (key-chord-define-global "yi" (lambda ()
                                  "Switch to org agenda."
                                  (interactive)
                                  (if (get-buffer "*Org Agenda*")
                                      (switch-to-buffer (get-buffer "*Org Agenda*"))
                                    (org-agenda-list))))
  (key-chord-define-global "kx" (lambda () (interactive)
                                  (if (eq major-mode 'org-mode)
                                      (org-edit-special)
                                    (org-edit-src-exit))))
  (key-chord-define-global "1'" #'org-previous-visible-heading)
  (key-chord-define-global "jk" (lambda () (interactive)
                                  (cond
                                   ((eq major-mode 'Buffer-menu-mode) (ibuffer))
                                   (t (list-buffers)))))
  (key-chord-define-global "n1" #'sp-narrow-to-sexp)
  (key-chord-define-global "n2" #'mw-narrow-to-up-sexp)
  ;; (key-chord-define-global "a7" #'mw-set-extra-point)
  ;; (key-chord-define-global "a8" #'mw-goto-extra-point)
  (key-chord-define-global "a6" #'ariadne-marks-goto-end)
  (key-chord-define-global "a7" #'ariadne-marks-backward)
  (key-chord-define-global "a8" #'ariadne-marks-set-mark)
  (key-chord-define-global "a9" #'ariadne-marks-unset)
  (key-chord-define-global "a0" #'ariadne-marks-unset-all)
  (key-chord-define-global "c1" #'chronos-add-timer)
  (key-chord-define-global "d1" #'mw-org-link-remove-file-decoration)
  (key-chord-define-global "s1" #'slime-repl)
  (key-chord-define-global "y5" #'kmacro-start-macro-or-insert-counter)
  (key-chord-define-global "f6" #'kmacro-call-macro) ; need
                                        ; non-key-chord
                                        ; to end macro
                                        ; AFAICS.
  (key-chord-define-global "--" (lambda () (interactive) (insert "_")))
  )
#+END_SRC


*** paredit
:PROPERTIES:
:ID:       ce94c391-0d41-4ef9-95f2-979cd85d9fa3
:END:

Very helpful mode for editing elisp.

#+BEGIN_SRC emacs-lisp
(use-package paredit
  :ensure t
  ;; :config (progn
  ;;           (add-hook 'emacs-lisp-mode-hook (lambda () (paredit-mode t)))
  ;;           (define-key paredit-mode-map  (kbd "M-s") nil) ; Unshadow all the M-s standard stuff.
  ;;           )
  :bind ("C-M-<up>" . paredit-splice-sexp))
#+END_SRC


*** Lispy
:PROPERTIES:
:ID:       dc92f6e4-01ae-4f78-8846-76aad2457c2d
:END:

#+BEGIN_SRC emacs-lisp
(use-package lispy
  ;; :config
  ;; (define-key lispy-mode-map-lispy (kbd "]") nil)
  ;; (define-key lispy-mode-map-lispy (kbd "[") nil)
  )

(setf
 lispy-mode-hook
 (lambda ()
   (key-chord-define-local "[0" (lambda () (interactive) (insert "[")))
   (key-chord-define-local "]1" (lambda () (interactive) (insert "]")))))
#+END_SRC

*** smartparens
:PROPERTIES:
:ID:       11c6416f-02e7-43e5-8b77-a4760525e11f
:END:

[2016-01-08 Fri 14:49] At first I thought smartparens-mode will replace paredit for me.  But
somehow I always come back to paredit.

#+BEGIN_SRC emacs-lisp
(use-package smartparens
  :ensure t
  :config (turn-on-smartparens-mode))
#+END_SRC

*** gnorb
:PROPERTIES:
:ID:       50b10169-5b1b-4af8-8eed-ba3f5d387525
:END:

gnorb is integration of gnus and org and bbdb .

#+BEGIN_SRC emacs-lisp
(use-package gnorb)

(require 'gnorb)
(require 'gnorb-org)
(require 'gnorb-gnus)
(gnorb-tracking-initialize)

(eval-after-load "gnorb-bbdb"
  '(progn
     (define-key bbdb-mode-map (kbd "O") 'gnorb-bbdb-tag-agenda)
     (define-key bbdb-mode-map (kbd "S") 'gnorb-bbdb-mail-search)
     (define-key bbdb-mode-map [remap bbdb-mail] 'gnorb-bbdb-mail)
     (define-key bbdb-mode-map (kbd "l") 'gnorb-bbdb-open-link)
     (global-set-key (kbd "C-c C") 'gnorb-bbdb-cite-contact)))

(eval-after-load ;; "gnorb-org"
  "org"
  '(progn
     (org-defkey org-mode-map (kbd "C-c C") 'gnorb-org-contact-link)
     (org-defkey org-mode-map (kbd "C-c m") 'gnorb-org-handle-mail)
     (org-defkey org-mode-map (kbd "C-c e") 'gnorb-org-view)
     (org-defkey org-mode-map (kbd "C-c E") 'gnorb-org-email-subtree)
     (org-defkey org-mode-map (kbd "C-c V") 'gnorb-org-popup-bbdb)
     (setq gnorb-org-agenda-popup-bbdb t)
     (eval-after-load "org-agenda"
       '(progn ;; (org-defkey org-agenda-mode-map (kbd "C-c t") 'gnorb-org-handle-mail)
               (org-defkey org-agenda-mode-map (kbd "C-c v") 'gnorb-org-popup-bbdb)
               (org-defkey org-agenda-mode-map (kbd "V") 'gnorb-org-view)))))

(eval-after-load "gnorb-gnus"
  '(progn
     (define-key gnus-summary-mime-map "a" 'gnorb-gnus-article-org-attach)
     (define-key gnus-summary-mode-map (kbd "C-c t") 'gnorb-gnus-incoming-do-todo)
     (define-key gnus-summary-mode-map (kbd "C-c e") 'gnorb-gnus-view)
                                        ; this is 'e' because of the
                                        ; respective binding for
                                        ; org-view suggested in the
                                        ; docu [2015-05-28 Thu 08:54].
     (push '("attach to org heading" . gnorb-gnus-mime-org-attach)
           gnus-mime-action-alist)
     ;; The only way to add mime button command keys is by redefining
     ;; gnus-mime-button-map, possibly not ideal. Ideal would be a
     ;; setter function in gnus itself.
     (push '(gnorb-gnus-mime-org-attach "a" "Attach to Org heading")
           gnus-mime-button-commands)
     (setq gnus-mime-button-map
           (let ((map (make-sparse-keymap)))
             ;; (define-key map gnus-mouse-2 'gnus-article-push-button)
             ;; (define-key map gnus-down-mouse-3 'gnus-mime-button-menu)
             (dolist (c gnus-mime-button-commands)
               (define-key map (cadr c) (car c)))
             map))))

(eval-after-load "message"
  '(progn
     (define-key message-mode-map (kbd "C-c t") 'gnorb-gnus-outgoing-do-todo)))
#+END_SRC

*** rase
:PROPERTIES:
:ID:       840cc11e-5a99-49d6-a091-72fae9c03e0d
:END:

=rase= is for triggering actions at sunrise and sunset.

Reversing the colors of Emacs at sunrise and at sunset.

#+BEGIN_SRC emacs-lisp
(use-package rase
  :config
  (add-hook
   'rase-functions
   (lambda (sun-event &optional first-run)
     (cond
      (first-run (let ((solar-rise-set  (solar-sunrise-sunset (calendar-current-date)))
                       (time-of-day (mw-current-time-of-day-decimal)))
                   ;; ((7.749999999068677 "CET") (17.5166666675359 "CET") "9:46")
                   (if (or (< time-of-day (caar solar-rise-set))
                           (<= (caadr solar-rise-set) time-of-day))
                    (load-theme 'reverse))))
      ((eq sun-event 'sunrise)
       (disable-theme 'reverse)
       ;; (setf (cdr (assoc 'reverse default-frame-alist)) nil) ;; Change params for next frame creation.
       )
      ((eq sun-event 'sunset)
       (load-theme 'reverse t)
       ;; (setf (cdr (assoc 'reverse default-frame-alist)) t) ;; Change params for next frame creation.
       ))))

  ;; Realization with make-frame which is a bit hackish.
  ;; (add-hook
  ;;  'rase-functions
  ;;  (lambda (sun-event &optional first-run)
  ;;    (unless first-run
  ;;      (if (or (eq sun-event 'sunrise) (eq sun-event 'sunset))
  ;;          (run-at-time "1 sec" ; one sec after the event the parameters shall be ready.
  ;;                       nil #'make-frame)))))

  ;; The following lines are here for remember how to use 'advice'.
  ;; Possibly an alternative is `before-make-frame-hook'.
  ;;
  ;; (advice-add 'make-frame :before
  ;;             (lambda (&optional parameters) (when mw-make-frame-first-call
  ;;                          (setq mw-make-frame-first-call nil)
  ;;                          (rase-start t))))

  (run-at-time "20 sec" nil (lambda () (rase-start t))) ;; Pragmatic, not nice.
  ;; (rase-start t) ;; This line is not enough to change the theme.
  )
#+END_SRC

*** AUR access
:PROPERTIES:
:ID:       5c3c8a77-546a-4260-b415-d73b822e76c2
:END:

~aurel~ helps with the management of the AUR-packages of the
Arch-Linux system.

#+BEGIN_SRC emacs-lisp
(use-package aurel
  :config
  (autoload 'aurel-package-info "aurel" nil t)
  (autoload 'aurel-package-search "aurel" nil t)
  (autoload 'aurel-maintainer-search "aurel" nil t)
  (autoload 'aurel-installed-packages "aurel" nil t)
  (setq aurel-download-directory "~/AUR"))
#+END_SRC

**** history

- [2014-04-07 Mon 22:26] Just installed a package that might help with
AUR-packages.

*** zeitgeist
:PROPERTIES:
:ID:       c93d05fd-70f4-43fa-9a5a-9ea24e098e7e
:END:

The zeitgeist software keeps track of file-operations.  Not sure if I
have this still up.

#+BEGIN_SRC emacs-lisp
(use-package zeitgeist :disabled)
#+END_SRC

**** TODO Check the zeitgeist stuff                                :noexport:
*** helm
:PROPERTIES:
:ID:       277e966f-aa7b-4785-b7d2-f3516910009a
:END:

Actually i don't use helm consciously.  [2015-06-27 Sat 10:57]

#+BEGIN_SRC emacs-lisp
(use-package helm)
#+END_SRC

[2016-04-29 Fri 14:31] I do use helm-emms to switch on bassdrive.

*** gnuplot
:PROPERTIES:
:ID:       46863a10-761b-4483-8d3a-8a289850e819
:END:

The following lines go back to a recommendation of an arch linux
install.

#+BEGIN_SRC emacs-lisp
(use-package gnuplot
  :config (progn
            (autoload 'gnuplot-mode "gnuplot" "gnuplot major mode" t)
            (autoload 'gnuplot-make-buffer "gnuplot" "open a buffer in gnuplot mode" t)
            (setq auto-mode-alist (append '(("\\.gp$" . gnuplot-mode)) auto-mode-alist))))
#+END_SRC

*** hydra
:PROPERTIES:
:ID:       8b5cc921-e0bb-410d-86e6-d7598f8eb2a7
:END:

Hydra provides some convenient key maps organization.

#+BEGIN_SRC emacs-lisp
(use-package hydra)
#+END_SRC

*** sotlisp
:PROPERTIES:
:ID:       f09730a1-c8ef-4be2-84a9-d2dec56fbd1c
:END:

Helpful for jumping around!

#+BEGIN_SRC emacs-lisp
(use-package sotlisp)
#+END_SRC

*** nyan-mode
:PROPERTIES:
:ID:       13a7baa3-2b09-4239-bd29-fb01966bf211
:END:

#+BEGIN_SRC emacs-lisp
(use-package nyan-mode
  :config (nyan-mode))
#+END_SRC

*** git-auto-commit-mode
:PROPERTIES:
:ID:       70ec63c9-3eaf-405b-b159-084a7c8fb207
:END:

#+BEGIN_SRC emacs-lisp
(use-package git-auto-commit-mode
:ensure t
:config (git-auto-commit-mode t))
#+END_SRC

*** epa
:PROPERTIES:
:ID:       1d2839a8-b4a8-47ae-9d7a-6dab21dc5b80
:END:

#+BEGIN_SRC emacs-lisp
(require 'epa)
(define-key epa-key-list-mode-map "N" #'mw-epa-mark-next-key)
#+END_SRC

** LabPkgs

*** hyperbole
:PROPERTIES:
:ID:       8963d400-1720-4887-b113-b0e90dddb43b
:END:

Give hyperbole a try.

#+BEGIN_SRC emacs-lisp
;; (require 'package)
;; (setq package-enable-at-startup nil) ;; Prevent double loading of libraries
;; (package-initialize)
;; (unless (package-installed-p 'hyperbole)
;;   (package-refresh-contents)
;;   (package-install 'hyperbole))

;;;; (require 'hyperbole)

#+END_SRC

#+BEGIN_SRC emacs-lisp
;; (org-defkey org-mode-map (kbd "<C-M-return>") #'hkey-either)

;;;; (global-set-key (kbd "C-M-7") #'hkey-either)
;;;; (global-set-key (kbd "C-M-8") #'assist-key)

(add-hook 'org-mode-hook
          (lambda () (local-set-key [f10] #'org-time-stamp)))
(add-hook 'org-mode-hook
          (lambda () (local-set-key (kbd "C-c .") ; no success to override of the hyperbole 'C-c .' like so.
                               'org-time-stamp)))
(eval-after-load "org"
  '(progn
     (org-defkey org-mode-map (kbd "C-c r") #'org-reveal)))
;; override a binding of hyperbole for org-mode
#+END_SRC

*** emr
:PROPERTIES:
:ID:       910630f4-e846-4fd6-8772-4e9f46ff99d7
:END:

emr is a refactoring tool.

#+BEGIN_SRC emacs-lisp
(use-package emr
   :config (progn
            ;; (autoload 'emr-show-refactor-menu "emr")
             (eval-after-load "emr" '(emr-initialize)))
   ;; :bind ("M-RET" . emr-show-refactor-menu)
   )
#+END_SRC

**** TODO Show the emr menu with M-RET                             :noexport:

*** beacon
:PROPERTIES:
:ID:       735f3e2f-3a98-4b36-b30e-1e86945efca0
:END:

#+BEGIN_SRC emacs-lisp
(use-package beacon
  :ensure t
  :defer 1 ; else can't start as daemon like /home/b/p/emacs-build/lib-src/emacsclient -c -n -a \"\"
  :config (beacon-mode 1))
#+END_SRC

*** elmacro
:PROPERTIES:
:ID:       57c20c8f-995f-4369-8ef5-65cfc4956638
:END:

I can only remember that I liked the name and the idea of this
package.

#+BEGIN_SRC emacs-lisp
(use-package elmacro
:ensure t)
#+END_SRC

**** TODO What is this?                                            :noexport:

*** git-timemachine
:PROPERTIES:
:ID:       ee4ea8cb-e93a-4dd5-ae0d-3bf311c45023
:END:

#+BEGIN_SRC emacs-lisp
(use-package git-timemachine
:ensure t)
#+END_SRC

Start git-timemachine on a file to travel time on it.

;;; From: Source:

(add-to-list 'load-path "~/p/elisp/external/lentic")
(add-to-list 'load-path "~/p/elisp/external/m-buffer-el")
(require 'lentic-mode)
(global-lentic-mode)
*** refine
:PROPERTIES:
:ID:       f9e04b7d-515c-4dbf-b172-1fea2d5790b7
:END:

Package for editing lists.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/p/elisp/external/refine")
(require 'refine)
#+END_SRC

*** slime

**** the local-git slime
:PROPERTIES:
:ID:       488225b9-bce0-4031-a753-f5b124b3f625
:END:

#+BEGIN_SRC emacs-lisp
;; (add-to-list 'load-path "~/p/elisp/external/slime")
;; (require 'slime-autoloads)
;; (setq inferior-lisp-program "/usr/bin/sbcl")
;; (setq slime-contribs '(slime-fancy))
;; (eval-after-load 'info
;;   '(progn (info-initialize)
;;           (add-to-list 'Info-directory-list
;;                        "~/p/elisp/external/slime/doc")))
#+END_SRC

**** the quicklisp slime
:PROPERTIES:
:ID:       24a75320-5d6f-48b4-a716-e17be2db42fc
:END:

CL-USER> (ql:quickload "quicklisp-slime-helper")
To use, add this to your ~/.emacs:

#+BEGIN_SRC emacs-lisp
(load (expand-file-name "~/p/quicklisp/slime-helper.el"))
(setq inferior-lisp-program "sbcl")
#+END_SRC

**** hyperspec access
:PROPERTIES:
:ID:       052ca2b7-a6b2-44ce-acba-d519c35e9e1c
:END:

common-lisp-hyperspec-root is a variable defined in ‘hyperspec.el’.
Its value is "http://www.lispworks.com/reference/HyperSpec/"

Documentation:
The root of the Common Lisp HyperSpec URL.
If you copy the HyperSpec to your local system, set this variable to
something like "file://usr/local/doc/HyperSpec/".

#+BEGIN_SRC emacs-lisp
(add-hook
 'slime-mode-hook
 (lambda ()
   (setq common-lisp-hyperspec-root "file:///home/b/media/texts/it/lisp/HyperSpec/")))
#+END_SRC

*** Org                                                                 :org:

**** Org todo dependencies
:PROPERTIES:
:ID:       ca70c911-9c5a-4d07-b499-9b854fed6e07
:END:

Activate dependency checks.

#+BEGIN_SRC emacs-lisp
(setq org-enforce-todo-dependencies t)
#+END_SRC

**** Personal Org Indentation
:PROPERTIES:
:ID:       fef018c8-f725-47ef-8608-ef2045b88cfa
:END:

#+BEGIN_SRC emacs-lisp
(setq org-adapt-indentation nil
      org-hide-leading-stars t
      org-odd-levels-only t)
#+END_SRC

**** To Org Attachments
:PROPERTIES:
:ID:       26bf9d8b-f6aa-40db-bf28-3ed5e8efef88
:END:

#+BEGIN_SRC emacs-lisp
(setq org-attach-commit nil)
#+END_SRC

**** Org Agenda include inactive timestamps
:PROPERTIES:
:ID:       df559437-3db6-4198-8878-c18efbbe0f33
:END:

#+BEGIN_SRC emacs-lisp
(setq org-agenda-include-inactive-timestamps t) ;;
;; (setq org-agenda-include-inactive-timestamps nil) ;; for not seeing them.
#+END_SRC

**** Org column settings
:PROPERTIES:
:ID:       5bed4d4e-1d89-4cd8-8af9-f8ff04009a6c
:END:

#+BEGIN_SRC emacs-lisp
(setq
 org-columns-ellipses "…"
 org-columns-default-format "%ITEM %TODO %PRIORITY %TAGS")
#+END_SRC

**** Org Babel

***** Jump to org block bound
:PROPERTIES:
:ID:       304ea5c8-51b5-4c79-a945-a3c0cd200d21
:END:

The following bindings allow to find the next occurance of string '#+'
which typically indicate an org-block meta thing.

#+BEGIN_SRC emacs-lisp
(add-hook
 'org-mode-hook
 (lambda ()
   (local-set-key
    (kbd "C-c M-n")
    (lambda ()
      (interactive)
      (end-of-line)
      (re-search-forward "#\\+")
      (beginning-of-line)))))

(add-hook
 'org-mode-hook
 (lambda ()
   (local-set-key
    (kbd "C-c M-p")
    (lambda ()
      (interactive)
      (beginning-of-line)
      (re-search-backward "#\\+")))))
#+END_SRC

There are useful bindings in connection with org-blocks already built
in, e.g. org-next-block which sets point to the /beginning/ of the
next block.

***** Tab jump from code-block 'end' to 'begin'
:PROPERTIES:
:ID:       d0679e88-199a-4036-99f2-5aeb1995dd4a
:END:

#+BEGIN_SRC emacs-lisp
;; Experimentation for more convenient block handling.
(defun mw-org-jump-to-beginning-of-block-maybe ()
  "When on a closing line of a block jump to the opening line of the block."
  (interactive)
  (let ((case-fold-search t)
        (org-block-end-line-regexp "^[ \t]*#\\+end_")
        (org-block-begin-line-regexp  "^[ \t]*#\\+begin_"))
    (when (save-excursion
            (beginning-of-line 1)
            (looking-at org-block-end-line-regexp))
      (progn
        (search-backward-regexp org-block-begin-line-regexp)
        t ;; signal that action has been taken
        ))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; Use tab-key for trigger the action.  This is done via hooking.
(eval-after-load 'org
  (lambda ()
    (add-to-list 'org-tab-first-hook 'mw-org-jump-to-beginning-of-block-maybe)))
#+END_SRC

***** Convenient go up to the beginning of a block
:PROPERTIES:
:ID:       999d0bbe-9e0b-43f6-9fb2-9bf367081cf0
:END:

#+BEGIN_SRC emacs-lisp
;; Experimentation for more convenient block handling.
(defun mw-org-search-backward-beginning-of-block ()
  "When on a closing line of a block jump to the opening line of the block."
  (interactive)
  (let ((case-fold-search t)
        (org-block-begin-line-regexp  "^[ \t]*#\\+begin_"))
        (search-backward-regexp org-block-begin-line-regexp)))
#+END_SRC

***** More key bindings for babeling
:PROPERTIES:
:ID:       7b38b04a-1ce9-48fc-a460-17562527b750
:END:

#+BEGIN_SRC emacs-lisp
(require 'ob-keys)

(setq
 org-babel-key-bindings
 (append
  org-babel-key-bindings
  (list
   (cons "m" #'org-babel-mark-block)
   (cons "N" #'org-narrow-to-block)
   (cons "'" #'org-edit-special)
   (cons ">" ; jump to the end.
         (lambda () (let ((case-fold-search t)) ; don't care about case.
                 (search-forward-regexp "#\\+end_src")
                 (beginning-of-line)))))))
#+END_SRC

**** Org Velocity
:PROPERTIES:
:ID:       6a1165bb-f429-463a-ace1-05bb7c59c4d7
:END:

org velocity is a org-mode contrib extension.

#+BEGIN_SRC emacs-lisp
(setq org-velocity-bucket (expand-file-name "bucket.org" org-directory))
#+END_SRC

***** History

First i hung the C-c v in on org-mode-hook [2014-10-22 Wed 10:25] like

#+BEGIN_SRC text
(add-hook 'org-mode-hook (lambda () (local-set-key (kbd "C-c v") 'org-velocity)))
#+END_SRC

which is nice but actually org-velocity is also capable of a global
capturing into the org-velocity-bucket.  This is a further possibility
to capture something.

I use the global key setting C-c v for org-velocity.

**** org-protocol for receiving from the outside
:PROPERTIES:
:ID:       833fb525-34bb-4403-aa83-0853ccce0088
:END:

#+BEGIN_SRC emacs-lisp
(require 'org-protocol)
#+END_SRC

The org-protocol is useful for actions which come from the outside.
E.g. capturing from conkeror into org.

**** Highlight current line in agenda
:PROPERTIES:
:ID:       e9df3a2c-6adb-4687-a36f-8810c07ae578
:END:

From [[gnus:nntp+news.gmane.org:gmane.emacs.orgmode#87egnh7oos.fsf@mbork.pl][Email from Marcin Borkowski: Hl-line mode in agenda]]:

#+BEGIN_SRC emacs-lisp
(add-hook 'org-agenda-finalize-hook (lambda () (hl-line-mode 1)))
#+END_SRC

**** Save the o-press when opening the agenda
:PROPERTIES:
:ID:       fd89d958-98f7-4668-9d5d-3d2f9d92115f
:END:

#+BEGIN_SRC emacs-lisp
;(add-hook 'org-agenda-finalize-hook (lambda () (delete-other-windows)))
;; (setq org-agenda-window-setup 'only-window)
#+END_SRC

***** Source

http://mbork.pl/2015-09-26_A_few_org-agenda_hacks

**** Delete other windows after jump from agenda
:PROPERTIES:
:ID:       8b469c82-b9f8-47d6-8501-b4ef64c5b67d
:END:

#+BEGIN_SRC emacs-lisp
;; (eval-after-load "org-agenda"
;;   '(push #'delete-other-windows org-agenda-after-show-hook))
#+END_SRC

**** org-screenshot
:PROPERTIES:
:ID:       e5fc742e-7d15-4c37-8fc1-78ab99b2ba2d
:END:

using org-screenshot as a package now.

#+BEGIN_SRC emacs-lisp
;; (push "~/p/elisp/external/org-attach-screenshot" load-path)
;; (require 'org-attach-screenshot)
#+END_SRC

screenshots for orgees.  in particular during capturing.

#+BEGIN_SRC emacs-lisp
(defun mw-org-attach-screenshot-as-standard-attachment ()
  "Trigger ‘org-attach-screenshot’ with target as Org standard attachment.
Create the attachment dir if not exists.

The enhancement compared with pure org-attach-screenshot is that
no decision about how to store the image has to be made.
"
  (interactive)
  (require 'org-attach)
  (org-attach-dir t)
  (org-attach-screenshot
   nil
   (format-time-string
    "screenshot-%Y%m%d-%H%M%S.png"))
  (org-attach-sync))
#+END_SRC

Define a shortcut key:

#+BEGIN_SRC emacs-lisp
(add-hook
 'org-mode-hook
 (lambda ()
   (key-chord-define-local
    "t1" #'mw-org-attach-screenshot-as-standard-attachment)))
#+END_SRC

**** Disable key C-,
:PROPERTIES:
:ID:       67717574-2742-494f-90f2-33b92ee81baa
:END:

Want C-, not bound to org-cycle-agenda-files, which is also on C-'
anyways.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook (lambda ()
                           (local-unset-key (kbd "C-,"))
                           ))
#+END_SRC

**** Jump from the agenda to the stars
:PROPERTIES:
:ID:       c71cdcc8-4135-4869-b9d7-4c1d73330a0b
:END:

In the agenda 'tab' per default jumps to the beginning of the headline
text.  For me it's a bit more convenient to jump to the beginning of
the stars.  Fortunately there is org-agenda-after-show-hook.

#+BEGIN_SRC emacs-lisp
(eval-after-load "org-agenda"
  '(push #'beginning-of-line org-agenda-after-show-hook))
#+END_SRC

**** Speed commands also on first char
:PROPERTIES:
:ID:       9aeec743-8b52-40c4-9b54-5faf04c54e84
:END:

#+BEGIN_SRC emacs-lisp
(setq org-use-speed-commands
      (lambda () (or (= (point-min) (point))
                (and (looking-at org-outline-regexp)
                     (looking-back "^\**")))))
#+END_SRC

Taken the looking around code from the documentation of
~org-use-speed-commands~.

**** Refile Targets Config
:PROPERTIES:
:ID:       edb7f61b-b12e-44d2-adf0-d7d0af042c0b
:END:

#+BEGIN_SRC emacs-lisp
(setq org-refile-targets
 (quote
  ((nil :maxlevel . 7)
    ;; (org-agenda-files :maxlevel . 1)
   )))
(setq org-refile-use-outline-path (quote file))
#+END_SRC

*** gnus
:PROPERTIES:
:ID:       76eb595e-d246-4828-92aa-e8aa746c4d15
:END:

#+BEGIN_SRC emacs-lisp
;; (push (expand-file-name "~/p/elisp/external/gnus/lisp") load-path)
;; (require 'gnus-load)
;; (require 'info)
;; (add-to-list 'Info-default-directory-list "~/p/elisp/external/gnus/texi/")
(setq gnus-registry-max-entries 500000)
(gnus-registry-initialize) ; gnorb wants that, see (info "(gnorb)Setup").
#+END_SRC

**** To html mail in gnus
:PROPERTIES:
:ID:       eab9b9c5-355b-47b1-83b9-71d54270a1a6
:END:

The following helps with html-mail in some cases.

Source: [[gnus:gnu.emacs.help#mailman.5546.1405582006.1147.help-gnu-emacs@gnu.org][Email from Tassilo Horn: Re: a dark theme?]]

#+BEGIN_SRC emacs-lisp
;; I don't think that has anything to do with themes, but SHR which renders
;; HTML mail in Gnus just picks bad colors to confirm with what's declared
;; in the HTML text.  But you can force it to require more contrast like
;; so:
(setq shr-color-visible-distance-min 10
      shr-color-visible-luminance-min 60)
#+END_SRC

*** ledger
:PROPERTIES:
:ID:       6cfc4835-cb82-4608-a0c4-2a7361bfd9ba
:END:

Refer to a local version of ledger.

#+BEGIN_SRC emacs-lisp
(push  (expand-file-name "~/p/ledger/lisp") load-path)
(autoload 'ledger-mode "ledger-mode" "ledger major mode")

(eval-after-load 'info
  '(progn (info-initialize)
          (add-to-list
           'Info-directory-list
           (expand-file-name "~/p/ledger/doc"))))

(setq ledger-reports
      '(("bal" "ledger -f %(ledger-file) bal")
        ("monthly bal" "ledger -p \"monthly from jan to jul\" -f %(ledger-file) bal")
        ("bal-2015" "ledger -p 2015 -f %(ledger-file) bal")
        ("bal-2014" "ledger -p 2014 -f %(ledger-file) bal")
        ("bal-2014-01" "ledger -p jan -f %(ledger-file) bal")
        ("bal-2014-02" "ledger -p feb -f %(ledger-file) bal")
        ("bal-2014-03" "ledger -p mar -f %(ledger-file) bal")
        ("bal-2014-04" "ledger -p apr -f %(ledger-file) bal")
        ("bal-2014-05" "ledger -p may -f %(ledger-file) bal")
        ("bal-2014-06" "ledger -p jun -f %(ledger-file) bal")
        ("bal-2014-07" "ledger -p jul -f %(ledger-file) bal")
        ("bal-2014-08" "ledger -p aug -f %(ledger-file) bal")
        ("bal-2014-09" "ledger -p sep -f %(ledger-file) bal")
        ("bal-2014-10" "ledger -p oct -f %(ledger-file) bal")
        ("bal-2014-11" "ledger -p nov -f %(ledger-file) bal")
        ("bal-2014-12" "ledger -p dec -f %(ledger-file) bal")
        ("bal01" "ledger -p jan -f %(ledger-file) bal")
        ("bal02" "ledger -p feb -f %(ledger-file) bal")
        ("bal03" "ledger -p mar -f %(ledger-file) bal")
        ("bal04" "ledger -p apr -f %(ledger-file) bal")
        ("bal05" "ledger -p may -f %(ledger-file) bal")
        ("bal06" "ledger -p jun -f %(ledger-file) bal")
        ("bal07" "ledger -p jul -f %(ledger-file) bal")
        ("bal08" "ledger -p aug -f %(ledger-file) bal")
        ("bal09" "ledger -p sep -f %(ledger-file) bal")
        ("bal10" "ledger -p oct -f %(ledger-file) bal")
        ("bal11" "ledger -p nov -f %(ledger-file) bal")
        ("bal12" "ledger -p dec -f %(ledger-file) bal")
        ("Vermögen Feb" "ledger -p feb -f %(ledger-file) bal Vermögen")
        ("Barkasse" "ledger -f %(ledger-file) bal Vermögen:Barkasse")
        ("Giro" "ledger -f %(ledger-file) bal Vermögen:GiroPB")
        ("Giro up to date" "ledger -f %(ledger-file) --end 2014-11-18 bal Vermögen:GiroPB")
        ("reg" "ledger -f %(ledger-file) reg")
        ("payee" "ledger -f %(ledger-file) reg @%(payee)")
        ("account" "ledger -f %(ledger-file) reg %(account)")
        ("bal toplevel only" "ledger -f %(ledger-file) --depth 1 bal")))
#+END_SRC

*** emms
:PROPERTIES:
:ID:       005ce28c-c1ba-4f5c-84cf-74145b1b7aff
:END:

Emms is for playing sound.  I use emms mostly for playing internet
radio.

BTW =emms-streams= has configured some nice stations AFAICT.

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/external/emms/lisp" load-path)
(require 'emms-setup)
(emms-devel)				; adds +/- in emms-buffer.
(emms-default-players)
(eval-after-load 'info
  '(progn (info-initialize)
          (add-to-list 'Info-directory-list "~/p/elisp/external/emms/doc")))
#+END_SRC

*** Big Brother DB
:PROPERTIES:
:ID:       11bf1040-515f-430a-81ac-1484a42c6308
:END:

#+BEGIN_SRC emacs-lisp
(push (expand-file-name "~/p/elisp/external/bbdb/lisp") load-path)
(require 'bbdb-loaddefs (expand-file-name "~/p/elisp/external/bbdb/lisp/bbdb-loaddefs.el"))
(bbdb-initialize 'gnus 'message 'anniv)
(bbdb-mua-auto-update-init 'gnus 'message)
(setq bbdb-mua-pop-up nil
      ;; bbdb-mua-pop-up-window-size 0.1
      bbdb-mua-update-interactive-p '(query . create)
      bbdb-mua-auto-update-p 'create ; st annoying.  disable with (setf bbdb-mua-auto-update-p nil)
      bbdb-update-records-p 'query
      ;; bbdb-ignore-message-alist
      ;;    '(("From" . "bugzilla-daemon"))
      )
(add-hook 'message-setup-hook 'bbdb-mail-aliases)
;; [2016-02-05 Fri 13:15] this is a try...
(add-hook 'bbdb-after-change-hook (lambda (arg) (bbdb-save)))
;; Source [[gnus:nntp+news.gmane.org:gmane.emacs.bbdb.user#m28u2z8m57.fsf@charm-ecran.irisa.fr][Email from Alan Schmitt: Re: can I auto save the bbdb f]]
;; ...[2016-02-05 Fri 13:15]
#+END_SRC

*** Zen reward mode
:PROPERTIES:
:ID:       1b87e4e3-743a-47eb-9b20-651cd45b7c2d
:END:

Get points for task-status-changes in org.  But where is the zen here?

#+BEGIN_SRC emacs-lisp
(push (expand-file-name "~/p/elisp/external/zen-reward-mode/") load-path)
(load-library "zen-reward-mode")
#+END_SRC

**** History

Found this in a newsgroup.  See the source for more info.

*** Little helpers
:PROPERTIES:
:ID:       527a2699-830c-49da-8377-24e62c08281c
:END:

My little collection of Emacs stuff.

#+BEGIN_SRC emacs-lisp
(push  (expand-file-name "~/p/elisp/mw/little-helpers") load-path)
(require 'little-helpers)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-<") #'mw-recenter-jump-to-top)
#+END_SRC

*** Little helpers
:PROPERTIES:
:ID:       beec8c1e-a1e6-4458-826b-caf10242f0d4
:END:

My little collection of Emacs stuff.

#+BEGIN_SRC emacs-lisp
(assert
 (not
  (reduce
   (lambda (not-found b)
     (if not-found
         (not (string= b (expand-file-name "~/p/elisp/mw/little-helpers")))))
   load-path :initial-value t)))
(require 'org-supplements)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-<") #'mw-recenter-jump-to-top)
#+END_SRC

*** Hide Buffer Part
:PROPERTIES:
:ID:       12452d25-be10-4303-8429-9b867d201a94
:END:

#+BEGIN_SRC emacs-lisp
(push  "~/p/elisp/mw/hide-buffer-part" load-path)
#+END_SRC

*** Auxies
:PROPERTIES:
:ID:       f1df9204-3090-4333-a5ab-4884d0556c82
:END:

Another collection of Emacs stuff.

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/auxies" load-path)
(require 'auxies-rest)
#+END_SRC

**** TODO Check the Source                                         :noexport:

- Does auxies look good?
  - The name is not so promising AFAICS.
- Can auxies be restructured.

**** Hacks
:PROPERTIES:
:ID:       d8b58f6a-d388-4212-a17d-a4bf9b0cbd0c
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/hacks" load-path)
(require 'hacks)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-\"") #'org-cycle-agenda-files-backwards)
#+END_SRC

**** Auxies-eww
:PROPERTIES:
:ID:       c5c38c29-acf8-4283-8977-ffef26e1176f
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/auxies" load-path)
(require 'auxies-eww)
#+END_SRC

** From source

* Auxilliaries
:PROPERTIES:
:ID:       06d23ad3-863e-49c9-a5f7-9acbd2a68fbc
:END:

** Org
:PROPERTIES:
:ID:       3e50b218-2b6a-461c-b023-4a86b9652ae7
:END:

#+BEGIN_SRC emacs-lisp
(defun ---agenda-buffers ()
  "Return agenda buffers in a list."
  (cl-remove-if-not
   (lambda (x)
     (set-buffer x)
     (eq major-mode 'org-agenda-mode))
   (buffer-list)))
#+END_SRC

* Keysettings
:PROPERTIES:
:ID:       87eef969-ff13-4812-9c4e-2c79f9c3f7c6
:END:

** imenu
:PROPERTIES:
:ID:       7c7d3dfd-a0cc-4003-8ddd-6dfdaeeccefb
:END:

imenu provides a mechanism to jump to locations of interest for
several file types, e.g. Org.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-*") 'imenu)
#+END_SRC

** iedit
:PROPERTIES:
:ID:       12098f10-f528-4a9f-9e51-190ad76fcba8
:END:

can help to edit all occurances of a variable.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-;") 'iedit-mode)
#+END_SRC

*** use case example

- narrow to a part of interest.
- have point on the word of interest.
- activate imenu-mode (C-;).
- edit the word.
- leave the mode with C-cc (or C-;).

** Rectangle
:PROPERTIES:
:ID:       0433147d-df2b-4fa6-938b-cdee6202fa60
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x r u") #'clear-register)
#+END_SRC

** Org
:PROPERTIES:
:ID:       4584f701-7645-43d1-bcee-553898f68989
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c v") 'org-velocity)
#+END_SRC

** Following org-mode links given in other modes
:PROPERTIES:
:ID:       056989f0-a039-4043-a776-6f102786518a
:END:

To be able to follow an org-mode link in an arbitrary file can be
nice, e.g. to get to the original from within a tangled file.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c o") 'org-open-at-point-global)
#+END_SRC

** Exit org src edit with C-cc
:PROPERTIES:
:ID:       36981807-e987-4918-bdf4-ad5fb09654cd
:END:

#+BEGIN_SRC emacs-lisp
(define-key org-src-mode-map "\C-c\C-c" 'org-edit-src-exit)
#+END_SRC

** Individual keymap
:PROPERTIES:
:ID:       21856110-1ce5-4833-99da-8db3aefe35de
:END:

#+BEGIN_SRC emacs-lisp
(defvar mw-individual-keymap
  (let ((map (make-sparse-keymap)))
    (define-key map "y" #'mw-moz-controller-hackish-insert-current-url-from-mozrepl)
    (define-key map "f" #'mw-kill-buffer-filename)
    (define-key map "g" #'git-auto-commit-mode)
    (define-key map "l" #'clone-indirect-buffer)
    (define-key map "a" #'mw-append-to-scratch)
    (define-key map "r" #'mw-auxies-toggle-default-frame-reverse-state)
    (define-key map "d" #'mw-mode-line-as-message)
    (define-key map "m" #'menu-bar-mode)
    (define-key map "h" #'mw-strip)
    (define-key map "F" #'fringe-mode)
    (define-key map "b"
      (lambda ()
        (interactive)
        (if emms-player-playing-p
            (emms-player-pause)
          (progn
            (mw-sound-set-enjoyable-volume)
            (emms-play-url "http://www.bassdrive.com/BassDrive.m3u")))))
    (define-key map "p" #'password-store-copy)
    (define-key map "P" #'org-toggle-pretty-entities)
    (define-key map "j" #'org-clock-goto)
    (define-key map  (kbd "C-j")
      (lambda nil "Add a note to the Org currently clocked."
        (interactive) (org-clock-goto) (org-add-note)))
    (define-key map "z" #'mw-auxies-delete-to-direction)
    (define-key map "k" #'key-chord-mode) ; sometimes i need turning it off and on again.
    (define-key map "c" #'calendar)
    (define-key map "q" (lambda (arg)
                          (interactive "P")
                          (if (equal arg '(4))
                              (unbury-buffer)
                            (bury-buffer))))
    (define-key map "u" #'unexpand-abbrev)
    (define-key map "i" #'ido-hacks-mode)
    (define-key map "w" #'org-refile-goto-last-stored)
                                        ; recall: from org-files there is already C-u C-u C-c C-w.
    (define-key map "<" #'mw-screen-exchange-slurp-insert)
    (define-key map ">" #'mw-screen-exchange-write-region)
    (define-key map "e" #'evil-mode)
    (define-key map "E" (lambda () "Erase org-stored-links" (interactive) (setq org-stored-links nil)))
    (define-key map "(" #'paredit-mode)
    (define-key map ")" #'lispy-mode)
    (define-key map "W" #'calc-embedded-word) ; recall 'q' to leave the mode.
    (define-key map "s" (lambda () (interactive) (switch-to-buffer "*scratch*")))
    (define-key map "o" #'mw-org-kill-new-outline-path) ; Has been useful for refile.
    (define-key map "t" #'mw-teleport-region-to-other-window)
    ;;     (define-key map "t" (lambda ()
    ;;                           "Switch the minibuffer externalization for new frames.
    ;; And delete all frames.
    ;; This works good when an Emacs daemon runs and thus allows
    ;; easily create a new frame."
    ;;                           (interactive)
    ;;                           (if (cdr (assoc 'minibuffer default-frame-alist))
    ;;                               (mw-unset-minibuffer-in-default-frame)
    ;;                             (mw-set-minibuffer-in-default-frame))
    ;;                           (mapc #'delete-frame (frame-list))
    ;;                           ))
    map)
  "Personal convenience keymap.")
(global-set-key (kbd "\C-z") mw-individual-keymap)
#+END_SRC

** Hydras
:PROPERTIES:
:ID:       834bc884-e391-4dd2-9adf-af03da2077cf
:END:

This was thought to switch buffers quickly.  The overhead at start is
too much for me though.  [2015-10-12 Mon 14:55]

#+BEGIN_SRC emacs-lisp
(defhydra hydra-buffer-cycling
  (global-map "C-x <right>")
  "buffer-switch-entry-right"
  ("<right>" next-buffer)
  ("<left>" previous-buffer))
(defhydra hydra-buffer-cycling-b
  (global-map "C-x <left>")
  "buffer-switch-entry-left"
  ("<right>" next-buffer)
  ("<left>" previous-buffer))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defhydra hydra-winsize (global-map "C-c ^")
  "Shrink window."
  ("6" shrink-window)
  ("^" enlarge-window)
  ("<" shrink-window-horizontally)
  (">" enlarge-window-horizontally))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defhydra hydra-font-control (global-map "C-c C-S-f")
  "Control the font."
  ("-" (set-face-attribute
        'default nil
        :height (max 0 (- (face-attribute 'default :height) 20))))
  ("+" (set-face-attribute
        'default nil
        :height (+ (face-attribute 'default :height) 20)))
  ("b" (set-face-attribute
        'default nil
        :weight 'bold))
  ("n" (set-face-attribute
        'default nil
        :weight 'normal))
  ("p" (set-face-attribute
        'default nil
        :family "profont") "profont")
  ("s" (set-face-attribute
        'default nil
        :family "sourcecodepro") "sourcecodepro")
  ("c" (set-face-attribute
        'default nil
        :family "courier") "courier")
  ("q" (ignore) "ok, quit" :exit t))
#+END_SRC

** Dired Key for Alternate up
:PROPERTIES:
:ID:       0481cbe3-19d9-43ce-91a1-70fd845ff864
:END:

Expand ~dired-mode-map~ with a key for opening parent directory as
alternate dired.

#+BEGIN_SRC emacs-lisp
(add-hook
 'dired-mode-hook
 (lambda ()
   (define-key dired-mode-map "`" #'mw-alternate-up)))
#+END_SRC

** Dired Key for Narrow
:PROPERTIES:
:ID:       9ef15de4-8f07-4466-b729-854a693d3ad3
:END:

Expand ~dired-mode-map~ with a key for filtering the list of files.

#+BEGIN_SRC emacs-lisp
(add-hook
 'dired-mode-hook
 (lambda () (define-key dired-mode-map "/" #'dired-narrow-regexp)))
#+END_SRC

** Go to last line in Buffer List
:PROPERTIES:
:ID:       37de8dcf-392d-419d-aa9a-f69f409e2010
:END:

#+BEGIN_SRC emacs-lisp
(add-hook
 'Buffer-menu-mode-hook
 (lambda ()
   (local-set-key
    ">" (lambda () (interactive)
          (end-of-buffer)
          (backward-char)))))
#+END_SRC

With M-> point goes to the last char (and not one before that.)

** Communication with Mozilla
:PROPERTIES:
:ID:       2ee535a1-6f7a-45c2-b42c-d012ede8b780
:END:

see individual key map

#+BEGIN_SRC emacs-lisp
#+END_SRC

** Various Keysettings
:PROPERTIES:
:ID:       a5e292d4-96d1-45b8-928f-9df99e1beb44
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<f1>") #'ignore) ;; e.g. for leaving the zone.
(global-set-key (kbd "<f6>") #'flyspell-mode)
(global-set-key (kbd "<f7>") #'cycle-ispell-language-and-input-method)
(global-set-key (kbd "M-<f7>") #'mw-cycle-ispell-completion-dict)
(global-set-key (kbd "C-$") #'ispell-complete-word)
(global-set-key (kbd "S-<f11>") #'mw-rotate-split)
(global-set-key (kbd "<f12>") #'org-list-insert-inactive-ts-item)
(global-set-key (kbd "<f5>") #'mw-rectangle-ephermal-enumerate-lines)

;; the following collides with parmode:
;; (global-set-key (kbd "C-M-<right>") #'next-buffer)
;; (global-set-key (kbd "C-M-<left>") #'previous-buffer)
;; [2015-10-12 Mon 15:03] trying key chords.

(global-set-key (kbd "<XF86AudioLowerVolume>") #'emms-volume-lower)
(global-set-key (kbd "<XF86AudioRaiseVolume>") #'emms-volume-raise)

(defhydra hydra-volume-control (global-map "C-c 1")
  "Volume control."
  ("1" (dotimes (_ 50) (emms-volume-lower)) "silence")
  ("2" (emms-volume-lower) "lower")
  ("3" (progn (dotimes (_ 50) (emms-volume-lower)) (dotimes (_ 25) (emms-volume-raise))) "half")
  ("4" (emms-volume-raise) "raise")
  ("5" (dotimes (_ 50) (emms-volume-raise)) "full")
  ("q" (ignore) "quit" :exit t))

(global-set-key (kbd "<XF86AudioMute>") #'mw-sound-0%)
(global-set-key (kbd "<XF86AudioNext>") #'mw-sound-100%)
(global-set-key (kbd "<XF86AudioPlay>") #'mw-sound-set-enjoyable-volume)

(global-set-key (kbd "C-x o") 'ace-window)

(global-set-key (kbd "C-x C-c") #'save-buffers-kill-emacs) ; also kill the daemon (catchwords: quit, exit)

;; cycle through amounts of spacing
(global-set-key (kbd "M-SPC") #'cycle-spacing)

(global-set-key (kbd "C-5") #'repeat)

(defun mw-direct-command-repeat (&optional arg)
  "Direct command Repeat.  With prefix arg show the candidate."
  (interactive "P")
  (funcall
   (if arg
       (function mw-message-last-command)
     (function mw-repeat-last-command))))

(global-set-key
 (kbd "C-6")
 #'mw-direct-command-repeat)

(define-key global-map (kbd "<f9>")
  (lambda (&optional prefix)
    "Try insert org-inactive-timestamp.  With prefix argument
  try insert yyyymmddhhmm.  Special in org-agenda: toggle
  inactive-timestamps-display."
    (interactive "P")
    (cond
     ((eq major-mode 'org-agenda-mode)
      (setq org-agenda-include-inactive-timestamps (eq nil org-agenda-include-inactive-timestamps))
      (org-agenda-redo))
     (t (if prefix
            (insert (format-time-string "%Y%m%d%H%M"))
          (org-insert-time-stamp nil t t))))))
#+END_SRC

* Triggers
:PROPERTIES:
:ID:       464102cc-43b3-48f9-bc96-07403d6d2f0e
:END:

Let Emacs say something at start.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-finalize-agenda-hook 'org-agenda-to-appt) ; I want this!
(appt-activate 1)    ; enable

;; (org-agenda-list)
;; (switch-to-buffer "*Org Agenda*")

;; Vision: Extend the following code to be like the computer in the
;; Heart of Gold.  E.g. be able to start a conversation like "Hey
;; Emacs, please make some tee!"
(start-process "play-a-sound" "*play-a-sound-output*"
               "espeak"
               "-v"
               ;; "en-swedish"
               "en"
               "-s"
               "155" ;; word speed
               "Hi guys! This is a fantastic day! Let's do something!")
#+END_SRC

* Lab

** reverse-words
:PROPERTIES:
:ID:       dee2134c-0e50-404f-a68a-82124eb6616e
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/reverse-words/dist" load-path)
(require 'reverse-words "reverse-words-0.0.0.el")
#+END_SRC

** Display Org-properties conveniently
:PROPERTIES:
:ID:       e5a42da8-fea8-4057-8b10-2b9ca1029c74
:END:

#+begin_src emacs-lisp
(defun org-display-org-properties ()
"Display Org properties in a dedicated window."
  (interactive)
  (assert (eq 'org-mode major-mode))
  (let ((range-property-block (org-get-property-block))
        (show-properties-buffer (get-buffer-create "*Org Properties")))
    (with-current-buffer show-properties-buffer
      (erase-buffer))
    (when range-property-block
      (append-to-buffer
       show-properties-buffer
       (car range-property-block) (cdr range-property-block)))
    (display-buffer show-properties-buffer)))
#+end_src

** Widen to show the sexp up
:PROPERTIES:
:ID:       5814cb6d-9e73-48cc-98fa-d4acd7b3814c
:END:

#+begin_src emacs-lisp
(defun mw-narrow-to-up-sexp ()
  "Go one level up in sexps and narrow to it."
  (interactive)
  (widen)
  (sp-narrow-to-sexp 1)
  (sp-backward-up-sexp))
#+end_src

** override special scroll-lock-mode behavior
:PROPERTIES:
:ID:       c6605b4c-1cf2-47b0-8a86-266e5a2c47a2
:END:

I prefer to have scroll lock style all the time.

#+BEGIN_SRC emacs-lisp
(defun scroll-lock-next-line (&optional arg)
  "Scroll up ARG lines keeping point fixed."
  (interactive "p")
  (or arg (setq arg 1))
  (scroll-lock-update-goal-column)
  ;; (if (pos-visible-in-window-p (point-max))
  ;;     (forward-line arg)
    (scroll-up arg)
    ;; )
  (scroll-lock-move-to-column scroll-lock-temporary-goal-column))
#+END_SRC

** txr-mode
:PROPERTIES:
:ID:       6b8c441d-50f3-46c6-823f-9b9e7f07be99
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/external/txr-mode" load-path)
(require 'txr-mode)
#+END_SRC

** teleport region
:PROPERTIES:
:ID:       e0d66cd9-ba5e-4026-83cf-4e6f0919ceea
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-teleport-region-to-other-window (start end)
  "Move region to position in other window."
  (interactive "r")
  (let ((buf (save-excursion
               (other-window 1)
               (current-buffer))))
    (when buf
      (with-current-buffer buf
        (push-mark))
      (append-to-buffer buf start end)
      (delete-region start end)
      (switch-to-buffer buf))))
#+END_SRC

** repeat
:PROPERTIES:
:ID:       3f92313b-cdc6-4168-b596-d13a905d3f0f
:END:

control of `repeat'

Linked to the binding of `repeat'.

#+BEGIN_SRC emacs-lisp

;; (global-set-key (kbd "C-M-5") #'repeat-message-last-command)

(defun repeat-message-last-command ()
  "Haha.  This function is not so helpful because it pollutes `last-repeatable-command'.
 Maybe fix somehow if time."
  (interactive)
  (message
   "%s <- last repeatable command. %s <- before last"
   last-repeatable-command
   repeat-previous-repeated-command))
#+END_SRC

** lab libraries
:PROPERTIES:
:ID:       6a7e74d4-fff6-4771-84ba-0612d29f01ae
:END:

Location of research emacs-libraries.

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/lab" load-path)
(require 'mw-mark)
#+END_SRC

** Ariadne
:PROPERTIES:
:ID:       c40b4f41-a75f-44d0-84a2-c650824359c6
:END:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/p/elisp/mw/ariadne-marks")
(require 'ariadne-marks)
#+END_SRC

*** Bindings with a hydra
:PROPERTIES:
:ID:       7ed0b08a-99b3-4dce-b96a-88e5af2d3898
:END:

#+BEGIN_SRC emacs-lisp
(defhydra hydra-ariadne (global-map "C-c C-a")
  "Ariadne bindings."
  ("SPC" (ariadne-marks-set-mark) "set a mark")
  ("b" (ariadne-marks-backward) "go to next mark (or last if not on a mark)")
  ("e" (ariadne-marks-goto-end) "goto last mark")
  ("k" (ariadne-marks-unset) "delete current mark")
  ("d" (ariadne-marks-unset-all) "delete all marks"))
#+END_SRC

** cursor-color-mode
:PROPERTIES:
:ID:       aeef29ac-d726-4a15-8b0d-fdab5812c0b7
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/cursor-color-mode" load-path)
(require 'cursor-color-mode)
#+END_SRC

** hack-time
:PROPERTIES:
:ID:       0eb75da4-c436-4a52-9597-f68a318137f5
:END:

#+BEGIN_SRC emacs-lisp
;; (push "~/p/elisp/mw/hack-time-mode" load-path)
;; (require 'hack-time-mode)
#+END_SRC

** carry-region
:PROPERTIES:
:ID:       1fe74b31-e22b-498b-9779-2e1649f50883
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/carry-region" load-path)
(require 'carry-region)
#+END_SRC

*** keybinding

#+begin_src
(local-set-key (kbd "C-c r") #'mw-carry-region-toggle)
(global-set-key (kbd "C-c r") #'mw-carry-region-toggle)
#+end_src

** org-bullets
:PROPERTIES:
:ID:       b43bd556-05c9-4d1a-be97-b1dca5bba221
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/external/org-bullets" load-path)
(require 'org-bullets)
#+END_SRC

** more avy-goto via one command

BEGIN_SR emacs-lisp
(defun mw-avy-goto-char (arg)
  "Call avy-goto-char variant dependend of universal-argument.
Double C-u for `avy-goto-char-in-line' else call `avy-goto-char'.
"
  (interactive "P")
  (cond
   ((equal '(16) arg)
    (call-interactively #'avy-goto-char-in-line))
   ((call-interactively #'avy-goto-char))))
END_SRCTEXTIFY org-link

** textifylink part
:PROPERTIES:
:ID:       f4d7f7d6-82aa-4b89-8321-a471290a3dce
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-org-link-textify ()
  "Replace the link at point with its description."
  (interactive)
  (when (org-in-regexp org-bracket-link-regexp 1)
    (let ((remove (list (match-beginning 0) (match-end 0)))
          (link (match-string-no-properties 1))
          (desc (match-string-no-properties 3)))
      (replace-match (or desc link)))))
#+END_SRC
** Pick often used pw from authinfo
:PROPERTIES:
:ID:       515fd637-b0bb-4710-8ece-17dfed8b4e54
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-password-for-marco.wahl@gmail.com ()
  "Kill passwort for user marco.wahl@gmail.com out of my authinfo."
  (interactive)
  (let* ((delay-to-callback 42)
         (target
          (kill-new
           (car (aref (aref (plist-get
                             (car
                              (auth-source-search :user  "marco.wahl@gmail.com"))
                             :secret)
                            2)
                      0)))))
    (run-with-timer
     delay-to-callback nil
     (lambda ()
       (setf kill-ring  (delete target kill-ring))))))
#+END_SRC

** org-structure-as-dirs-and-files
:PROPERTIES:
:ID:       0b4d8cb9-6b9c-4dc0-b01e-b908ad97ca66
:END:

org-structure-as-dirs-and-files.el
#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/lab/org-structure-as-dirs-and-files" load-path)
(require 'org-structure-as-dirs-and-files)
#+END_SRC

** org-teleport
:PROPERTIES:
:ID:       18368c44-5b4b-49ff-a6f7-4b3d5f8e5adf
:END:

I really like this.

source
http://kitchingroup.cheme.cmu.edu/blog/2016/03/18/Org-teleport-headlines/

#+begin_src emacs-lisp
(defun org-teleport (&optional arg)
  "Teleport the current heading to after a headline selected with avy.
With a prefix ARG move the headline to before the selected
headline.  With a numeric prefix, set the headline level.  If ARG
is positive, move after, and if negative, move before."
  (interactive "P")
  ;; Kill current headline
  (org-mark-subtree)
  (kill-region (region-beginning) (region-end))
  ;; Jump to a visible headline
  (let ((avy-all-windows t))
    (avy-with avy-goto-line (avy--generic-jump "^\\*+" nil avy-style)))
  (cond
   ;; Move before  and change headline level
   ((and (numberp arg) (> 0 arg))
    (save-excursion
      (yank))
    ;; arg is what we want, second is what we have
    ;; if n is positive, we need to demote (increase level)
    (let ((n (- (abs arg) (car (org-heading-components)))))
      (cl-loop for i from 1 to (abs n)
               do
               (if (> 0 n)
                   (org-promote-subtree)
                 (org-demote-subtree)))))
   ;; Move after and change level
   ((and (numberp arg) (< 0 arg))
    (org-mark-subtree)
    (goto-char (region-end))
    (when (eobp) (insert "\n"))
    (save-excursion
      (yank))
    ;; n is what we want and second is what we have
    ;; if n is positive, we need to demote
    (let ((n (- (abs arg) (car (org-heading-components)))))
      (cl-loop for i from 1 to (abs n)
               do
               (if (> 0 n) (org-promote-subtree)
                 (org-demote-subtree)))))

   ;; move to before selection
   ((equal arg '(4))
    (save-excursion
      (yank)))
   ;; move to after selection
   (t
    (org-mark-subtree)
    (goto-char (region-end))
    (when (eobp) (insert "\n"))
    (save-excursion
      (yank))))
  (outline-hide-leaves))
#+end_src
** misty-rose
:PROPERTIES:
:ID:       31ab3269-f8c8-4bad-a41d-4e3b3384983a
:END:

#+BEGIN_SRC emacs-lisp
(defun mistyrose ()
  (interactive)
  (set-background-color "mistyrose"))
#+END_SRC

** org-mime

#+begin_src
(require 'org-mime)
#+end_src

Use e.g. =org-mime-subtree= to mail a tree.

** org-section-numbers
:PROPERTIES:
:ID:       a613b467-845b-48db-a416-0d62f4d7e627
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/org-section-numbers" load-path)
(require 'org-section-numbers)
#+END_SRC

** tweet-this
:PROPERTIES:
:ID:       6e7fe962-d7dc-4036-90a3-5208847842a9
:END:

#+BEGIN_SRC emacs-lisp
(defun tweet-this (b e)
 (interactive "r")
 (twittering-update-status (buffer-substring b e)))
#+END_SRC

** bbdb-this
:PROPERTIES:
:ID:       708cae26-6304-4cc0-be6e-6451c5dc7f8e
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-bbdb-this (b e)
  "Ask bbdb about the region."
  (interactive "r")
  (bbdb (buffer-substring b e)))

(defun mw-bbdb-word-at-point ()
  "Ask bbdb about word at point."
  (interactive)
  (bbdb (thing-at-point 'word t)))
#+END_SRC

** Convenient Drill
:PROPERTIES:
:ID:       c864c6bb-253e-4a58-83c0-aaa6a733bb2c
:END:

#+BEGIN_SRC emacs-lisp
(let (agenda-buffer-for-drill)
  (defun mw-org-agenda-open-next-line-as-drill-item-set-source-buffer ()
    (interactive)
    (setf agenda-buffer-for-drill (current-buffer)))

  (defun mw-org-agenda-open-next-line-as-drill-item ()
    "Switch to next drill item.
Precondition:

 - The agenda contains a relevant heading in the next agenda
line.

 - The drill items have a very special form."
    (interactive)
    (set-buffer
     (or agenda-buffer-for-drill
         (get-buffer (car (---agenda-buffers)))))
    (mw-org-agenda-open-next-line-as-drill-item-set-source-buffer)
    (org-agenda-next-item 1)
    (org-agenda-goto)
    (org-narrow-to-element)
    (org-show-children)
    (outline-next-heading)
    (org-show-subtree)
    (delete-other-windows)))
#+END_SRC

** Play with url from mozrepl
:PROPERTIES:
:ID:       66d9b36a-20ce-4e42-9427-7a6cd62a520e
:END:

#+BEGIN_SRC emacs-lisp
(use-package moz-controller)
(moz-controller-global-on)

(defun eww-open-ff-page ()
  "Open current firefox url with eww."
  (interactive)
  (moz-controller-get-current-url)
  (sleep-for 1)
  (eww moz-controller-repl-output))

(defun mw-moz-controller-hackish-insert-current-url-from-mozrepl ()
  "Try to insert the current url from mozrepl at point.

Note: This function may fail sometimes even when mozrepl and
Emacs are in proper state.  This is due to the expectation that
the url has arrived in Emacs after some timespan.

NTH: Check if there is a callback variant to achive the
functionality."
  ;; see also `mw-eww-goto-moz-page'.  merge?
  (interactive)
  (moz-controller-get-current-url)
  (sleep-for 0 100)
  (yank))
#+END_SRC

** Separate Sunrise/Sunset for calendar

See diary file.

*** Provide a string with the sunset
:PROPERTIES:
:ID:       f4b4c313-3ef5-420c-918e-22afaa4ea146
:END:

:origin:
[[file:~/p/emacs/lisp/calendar/solar.el::defun%20solar-sunrise-sunset-string][Function: solar-sunrise-sunset-string]]
:END:

#+BEGIN_SRC emacs-lisp
(defun solar-sunrise-string (date &optional nolocation)
  "String of *local* times of sunrise and daylight on Gregorian DATE.
Optional NOLOCATION non-nil means do not print the location."
  (let ((l (solar-sunrise-sunset date)))
    (format
     "%s%s (%s hrs daylight)"
     (if (car l)
         (concat "Sunrise " (apply 'solar-time-string (car l)))
       "No sunrise")
     (if nolocation ""
       (format " at %s" (eval calendar-location-name)))
     (nth 2 l))))

(defun solar-sunset-string (date &optional nolocation)
  "String of *local* times of sunset, and daylight on Gregorian DATE.
Optional NOLOCATION non-nil means do not print the location."
  (let ((l (solar-sunrise-sunset date)))
    (format
     "%s%s (%s hrs daylight)"
     (if (cadr l)
         (concat "Sunset " (apply 'solar-time-string (cadr l)))
       "no sunset")
     (if nolocation ""
       (format " at %s" (eval calendar-location-name)))
     (nth 2 l))))
#+END_SRC

*** Create a calendar function
:PROPERTIES:
:ID:       e8eccb17-a229-4111-8f55-df98b2dc940d
:END:

:origin:
[[file:~/p/emacs/lisp/calendar/solar.el::defun%20diary-sunrise-sunset][Function: diary-sunrise-sunset]]
:END:

#+BEGIN_SRC emacs-lisp
(defun diary-sunrise ()
  "Local time of sunset as a diary entry.
Accurate to a few seconds."
  (or (and calendar-latitude calendar-longitude calendar-time-zone)
      (solar-setup))
  (solar-sunrise-string date))

(defun diary-sunset ()
  "Local time of sunset as a diary entry.
Accurate to a few seconds."
  (or (and calendar-latitude calendar-longitude calendar-time-zone)
      (solar-setup))
  (solar-sunset-string date))
#+END_SRC

Direct call like so:

#+BEGIN_EXAMPLE
(let ((date (calendar-current-date))) (diary-sunrise-sunset))
#+END_EXAMPLE

** Fira Code
:PROPERTIES:
:ID:       ead76a35-9c1c-423a-b382-dc6a44690885
:END:

The following was disappointing. [2016-07-18]
source: https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs

#+BEGIN_SRC emacs-lisp
;;(when (window-system)
;; (set-frame-font "Fira Code"))
;;(let ((alist '((33 . ".\\(?:\\(?:==\\|!!\\)\\|[!=]\\)")
;;              (35 . ".\\(?:###\\|##\\|_(\\|[#(?[_{]\\)")
;;              (36 . ".\\(?:>\\)")
;;              (37 . ".\\(?:\\(?:%%\\)\\|%\\)")
;;              (38 . ".\\(?:\\(?:&&\\)\\|&\\)")
;;              (42 . ".\\(?:\\(?:\\*\\*/\\)\\|\\(?:\\*[*/]\\)\\|[*/>]\\)")
;;              (43 . ".\\(?:\\(?:\\+\\+\\)\\|[+>]\\)")
;;              (45 . ".\\(?:\\(?:-[>-]\\|<<\\|>>\\)\\|[<>}~-]\\)")
;;              (46 . ".\\(?:\\(?:\\.[.<]\\)\\|[.=-]\\)")
;;              (47 . ".\\(?:\\(?:\\*\\*\\|//\\|==\\)\\|[*/=>]\\)")
;;              (48 . ".\\(?:x[a-zA-Z]\\)")
;;              (58 . ".\\(?:::\\|[:=]\\)")
;;              (59 . ".\\(?:;;\\|;\\)")
;;              (60 . ".\\(?:\\(?:!--\\)\\|\\(?:~~\\|->\\|\\$>\\|\\*>\\|\\+>\\|--\\|<[<=-]\\|=[<=>]\\||>\\)\\|[*$+~/<=>|-]\\)")
;;              (61 . ".\\(?:\\(?:/=\\|:=\\|<<\\|=[=>]\\|>>\\)\\|[<=>~]\\)")
;;              (62 . ".\\(?:\\(?:=>\\|>[=>-]\\)\\|[=>-]\\)")
;;              (63 . ".\\(?:\\(\\?\\?\\)\\|[:=?]\\)")
;;              (91 . ".\\(?:]\\)")
;;              (92 . ".\\(?:\\(?:\\\\\\\\\\)\\|\\\\\\)")
;;              (94 . ".\\(?:=\\)")
;;              (119 . ".\\(?:ww\\)")
;;              (123 . ".\\(?:-\\)")
;;              (124 . ".\\(?:\\(?:|[=|]\\)\\|[=>|]\\)")
;;              (126 . ".\\(?:~>\\|~~\\|[>=@~-]\\)"))))
;; (dolist (char-regexp alist)
;;   (set-char-table-range composition-function-table (car char-regexp)
;;                         `([,(cdr char-regexp) 0 font-shape-gstring]))))
#+END_SRC

[2016-08-24 Wed 09:02] next try
https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs
https://gist.github.com/mordocai/50783defab3c3d1650e068b4d1c91495

This works when using emacs --daemon + emacsclient
(add-hook 'after-make-frame-functions (lambda (frame) (set-fontset-font t '(#Xe100 . #Xe16f) "Fira Code Symbol")))
(add-hook 'after-make-frame-functions (lambda (frame) (set-fontset-font t '(#Xe100 . #Xe16f) "Fira Code Symbol")))
This works when using emacs without server/client

(set-fontset-font t '(#Xe100 . #Xe16f) "Fira Code Symbol")
(set-fontset-font t '(#Xe100 . #Xe16f) "Fira Code Symbol")
I haven't found one statement that makes both of the above situations work, so I use both for now

(defconst fira-code-font-lock-keywords-alist
  (mapcar (lambda (regex-char-pair)
            `(,(car regex-char-pair)
              (0 (prog1 ()
                   (compose-region (match-beginning 1)
                                   (match-end 1)
                                   ;; The first argument to concat is a string containing a literal tab
                                   ,(concat "    " (list (decode-char 'ucs (cadr regex-char-pair)))))))))
          '(("\\(www\\)"                   #Xe100) ;;;    ;; 
            ("[^/]\\(\\*\\*\\)[^/]"        #Xe101) ;    
            ("\\(\\*\\*\\*\\)"             #Xe102) ;    
            ("\\(\\*\\*/\\)"               #Xe103) ;    
            ("\\(\\*>\\)"                  #Xe104) ;    
            ("[^*]\\(\\*/\\)"              #Xe105) ;    
            ("\\(\\\\\\\\\\)"              #Xe106) ;    
            ("\\(\\\\\\\\\\\\\\)"          #Xe107) ;    
            ("\\({-\\)"                    #Xe108) ;    
            ("\\(\\[\\]\\)"                #Xe109) ;    
            ("\\(::\\)"                    #Xe10a) ;    
            ("\\(:::\\)"                   #Xe10b) ;    
            ("[^=]\\(:=\\)"                #Xe10c) ;    
            ("\\(!!\\)"                    #Xe10d) ;    
            ("\\(!=\\)"                    #Xe10e) ;    
            ("\\(!==\\)"                   #Xe10f) ;    
            ("\\(-}\\)"                    #Xe110) ;    
            ("\\(--\\)"                    #Xe111) ;    
            ("\\(---\\)"                   #Xe112) ;    
            ("\\(-->\\)"                   #Xe113) ;    
            ("[^-]\\(->\\)"                #Xe114) ;    
            ("\\(->>\\)"                   #Xe115) ;    
            ("\\(-<\\)"                    #Xe116) ;    
            ("\\(-<<\\)"                   #Xe117) ;    
            ("\\(-~\\)"                    #Xe118) ;    
            ("\\(#{\\)"                    #Xe119) ;    
            ("\\(#\\[\\)"                  #Xe11a) ;    
            ("\\(##\\)"                    #Xe11b) ;    
            ("\\(###\\)"                   #Xe11c) ;    
            ("\\(####\\)"                  #Xe11d) ;    
            ("\\(#(\\)"                    #Xe11e) ;    
            ("\\(#\\?\\)"                  #Xe11f) ;    
            ("\\(#_\\)"                    #Xe120) ;    
            ("\\(#_(\\)"                   #Xe121) ;    
            ("\\(\\.-\\)"                  #Xe122) ;    
            ("\\(\\.=\\)"                  #Xe123) ;    
            ("\\(\\.\\.\\)"                #Xe124) ;    
            ("\\(\\.\\.<\\)"               #Xe125) ;    
            ("\\(\\.\\.\\.\\)"             #Xe126) ;    
            ("\\(\\?=\\)"                  #Xe127) ;    
            ("\\(\\?\\?\\)"                #Xe128) ;    
            ("\\(;;\\)"                    #Xe129) ;    
            ("\\(/\\*\\)"                  #Xe12a) ;    
            ("\\(/\\*\\*\\)"               #Xe12b) ;    
            ("\\(/=\\)"                    #Xe12c) ;    
            ("\\(/==\\)"                   #Xe12d) ;    
            ("\\(/>\\)"                    #Xe12e) ;    
            ("\\(//\\)"                    #Xe12f) ;    
            ("\\(///\\)"                   #Xe130) ;    
            ("\\(&&\\)"                    #Xe131) ;    
            ("\\(||\\)"                    #Xe132) ;    
            ("\\(||=\\)"                   #Xe133) ;    
            ("[^|]\\(|=\\)"                #Xe134) ;    
            ("\\(|>\\)"                    #Xe135) ;    
            ("\\(\\^=\\)"                  #Xe136) ;    
            ("\\(\\$>\\)"                  #Xe137) ;    
            ("\\(\\+\\+\\)"                #Xe138) ;    
            ("\\(\\+\\+\\+\\)"             #Xe139) ;    
            ("\\(\\+>\\)"                  #Xe13a) ;    
            ("\\(=:=\\)"                   #Xe13b) ;    
            ("[^!/]\\(==\\)[^>]"           #Xe13c) ;    
            ("\\(===\\)"                   #Xe13d) ;    
            ("\\(==>\\)"                   #Xe13e) ;    
            ("[^=]\\(=>\\)"                #Xe13f) ;    
            ("\\(=>>\\)"                   #Xe140) ;    
            ("\\(<=\\)"                    #Xe141) ;    
            ("\\(=<<\\)"                   #Xe142) ;    
            ("\\(=/=\\)"                   #Xe143) ;    
            ("\\(>-\\)"                    #Xe144) ;    
            ("\\(>=\\)"                    #Xe145) ;    
            ("\\(>=>\\)"                   #Xe146) ;    
            ("[^-=]\\(>>\\)"               #Xe147) ;    
            ("\\(>>-\\)"                   #Xe148) ;    
            ("\\(>>=\\)"                   #Xe149) ;    
            ("\\(>>>\\)"                   #Xe14a) ;    
            ("\\(<\\*\\)"                  #Xe14b) ;    
            ("\\(<\\*>\\)"                 #Xe14c) ;    
            ("\\(<|\\)"                    #Xe14d) ;    
            ("\\(<|>\\)"                   #Xe14e) ;    
            ("\\(<\\$\\)"                  #Xe14f) ;    
            ("\\(<\\$>\\)"                 #Xe150) ;    
            ("\\(<!--\\)"                  #Xe151) ;    
            ("\\(<-\\)"                    #Xe152) ;    
            ("\\(<--\\)"                   #Xe153) ;    
            ("\\(<->\\)"                   #Xe154) ;    
            ("\\(<\\+\\)"                  #Xe155) ;    
            ("\\(<\\+>\\)"                 #Xe156) ;    
            ("\\(<=\\)"                    #Xe157) ;    
            ("\\(<==\\)"                   #Xe158) ;    
            ("\\(<=>\\)"                   #Xe159) ;    
            ("\\(<=<\\)"                   #Xe15a) ;    
            ("\\(<>\\)"                    #Xe15b) ;    
            ("[^-=]\\(<<\\)"               #Xe15c) ;    
            ("\\(<<-\\)"                   #Xe15d) ;    
            ("\\(<<=\\)"                   #Xe15e) ;    
            ("\\(<<<\\)"                   #Xe15f) ;    
            ("\\(<~\\)"                    #Xe160) ;    
            ("\\(<~~\\)"                   #Xe161) ;    
            ("\\(</\\)"                    #Xe162) ;    
            ("\\(</>\\)"                   #Xe163) ;    
            ("\\(~@\\)"                    #Xe164) ;    
            ("\\(~-\\)"                    #Xe165) ;    
            ("\\(~=\\)"                    #Xe166) ;    
            ("\\(~>\\)"                    #Xe167) ;    
            ("[^<]\\(~~\\)"                #Xe168) ;    
            ("\\(~~>\\)"                   #Xe169) ;    
            ("\\(%%\\)"                    #Xe16a) ;    
            ;; ("\\(x\\)"                   #Xe16b)     This ended up being hard to do properly so i'm leaving it out.
            ("[^:=]\\(:\\)[^:=]"           #Xe16c)  ;  
            ("[^\\+<>]\\(\\+\\)[^\\+<>]"   #Xe16d)  ;  
            ("[^\\*/<>]\\(\\*\\)[^\\*/<>]" #Xe16f)) ;  
          ))

(defun add-fira-code-symbol-keywords ()
  (font-lock-add-keywords nil fira-code-font-lock-keywords-alist))

[2016-11-13 Sun 14:47] disabled because sometimes these characters
come out not so nicely.
(add-hook 'prog-mode-hook
#'add-fira-code-symbol-keywords)
[2016-11-13 Sun 14:47] end of disable.

(remove-hook 'prog-mode-hook #'add-fira-code-symbol-keywords)

** Drop the leading stars from ITEMs in column view                              :org:
:PROPERTIES:
:ID:       54866367-7522-49ce-b865-094d9a15dc4d
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-org-columns-modify-value-for-display (column-title value)
  (if (string= "ITEM" (upcase column-title))
      value))

(setq org-columns-modify-value-for-display-function
      'mw-org-columns-modify-value-for-display)
#+END_SRC

** Move Word
:PROPERTIES:
:ID:       f7851e7a-3228-4262-940a-cab9eca4cf16
:END:

#+BEGIN_SRC emacs-lisp
(defhydra hydra-transport-word (global-map "C-c t")
  "Transport word left or right."
  ("n" (transpose-words 1))
  ("p" (transpose-words -1)))
#+END_SRC

** repeat per hydra
:PROPERTIES:
:ID:       1fe2ee1d-ea08-49fd-abe4-b748970cc976
:END:

#+BEGIN_SRC emacs-lisp
(defhydra hydra-repeat (global-map "C-c C-6")
  "Command repeat."
  ("6" (mw-direct-command-repeat)))
#+END_SRC

** Capitalize Word
:PROPERTIES:
:ID:       e144174c-c4f3-4161-90d9-b09a03930b5f
:END:

Slight change to capitalize.  Capitalize the word backwards when on
end of it.

#+BEGIN_SRC emacs-lisp
(defun mw-capitalize-word (arg)
  "At end of word capitalize it.  Else do `capitalize-word'.
Argument ARG see `capitalize-word'."
  (interactive "P")
  (unless arg
    (when (looking-at-p  "\\>")
      (backward-word))
    (setf arg 1))
  (capitalize-word arg)
  ;; (forward-char)
  )
#+END_SRC

[2016-09-06 Tue 11:31] not so happy with this command because
point gets stuck at the end of a word when repeating the command.
Just discovered capitalize-dwim.  What is capitalize-dwim?

#+BEGIN_SRC emacs-lisp
;; (global-set-key "\M-c" #'mw-capitalize-word)
(global-set-key "\M-c" #'capitalize-dwim)
#+END_SRC

See also `toggle-letter-case'.  I possibly reinvented the wheel some
AFAICS.  [2016-06-23 Thu 11:07]

Interesting how many little details one finds when realizing such easy
looking feature.

** Handle bottommost-tagged after sorting
:PROPERTIES:
:ID:       c9c32c4e-f1d0-4eb0-acf2-209f42819d5b
:END:

This was an attempt to keep an orgee at the bottom.  Switched to
define stuff in .dir-locals.el.

#+BEGIN_SRC emacs-lisp
;; (setf org-after-sorting-entries-or-items-hook
;;       (lambda ()
;;         (search-forward  ":bottommost:")
;;         (org-cut-subtree)
;;         (goto-char (point-max))
;;         (org-paste-subtree 1)))
#+END_SRC

** Double space at end of sentences
:PROPERTIES:
:ID:       4f8a68c5-f950-4aaa-9dee-5da99753e2ec
:END:

Function to convert single space sentence endings to double space.

#+BEGIN_SRC emacs-lisp
(defun if-sentence-end-space-make-it-space
    () (interactive)
    (let ((sentence-end-double-space nil))
      (forward-sentence)
      (when (looking-at " +") (replace-match "  "))))
#+END_SRC

** Maxima
:PROPERTIES:
:ID:       34329cbe-bfd6-477a-8e2d-f2790c89cca4
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/external/maxima" load-path)
(require 'maxima)
#+END_SRC

** Pick current agenda filter
:PROPERTIES:
:ID:       252fe790-d35f-4559-b9dd-7da3f4edb374
:END:

[2016-05-25 Wed 19:26] I wanted this.  Practise shall show if this
helps some.

#+BEGIN_SRC emacs-lisp
(defun mw-org-agenda-store-current-filters-as-custom-agenda ()
  "Make current setting of agenda a custom agenda \"x\" ."
  (interactive)
  (org-add-agenda-custom-command
   `("x" "Custom agenda" agenda ""
     ((org-agenda-overriding-header
       "Custom agenda")
      (org-agenda-tag-filter-preset
       ',org-agenda-tag-filter)
      (org-agenda-regexp-filter-preset
        ',org-agenda-regexp-filter)
      (org-agenda-category-filter-preset
       ',org-agenda-category-filter)))))
#+END_SRC
** Personalize emacs-lisp-mode

Set some personal stuff via customize.

** Prefix Lines with Timesstamp
:PROPERTIES:
:ID:       60e8371c-be2b-4aa0-aa5f-ea7ac19e2588
:END:

Prefix lines with a timesstamp.

Unclear yet: Is this the shit?

#+BEGIN_SRC emacs-lisp
(global-set-key
 (kbd "<f8>")
 (lambda ()
   (interactive)
   (newline)
   (org-insert-time-stamp nil t t)
   (insert " ")))
#+END_SRC

** org-crypt
:PROPERTIES:
:ID:       47a72486-e30d-4653-9a2a-dc5465c37580
:END:

#+BEGIN_SRC emacs-lisp
(eval-after-load 'org-crypt '(org-crypt-use-before-save-magic))
#+END_SRC

** jl-encrypt                                                         :crypto:
:PROPERTIES:
:ID:       b08f7a09-241a-4d66-adeb-44e02aa4b34b
:END:

Don't forget the crypto.

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/external/jl-encrypt" load-path)
(require 'jl-encrypt)
;; (add-hook 'gnus-message-setup-hook #'mml-secure-encrypt-if-possible)
;; (add-hook 'message-send-hook #'mml-secure-check-encryption-p)
#+END_SRC

** exwm
:PROPERTIES:
:ID:       04b85506-c926-4849-9a42-4ebc9fd647f7
:END:

#+BEGIN_SRC emacs-lisp
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
(require 'exwm-randr)

(setq exwm-randr-workspace-output-plist '(0 "VGA1"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output VGA1 --left-of LVDS1 --auto")))
(exwm-randr-enable)

#+END_SRC

** Jump to other Drawers                                                :org:
:PROPERTIES:
:ID:       d91359bd-684b-4e4a-b34b-ea873430660c
:END:

#+BEGIN_SRC emacs-lisp
(defun org-next-drawer (count)
  (interactive "p")
  (search-forward-regexp org-drawer-regexp nil nil count))

(defun org-previous-drawer (count)
  (interactive "p")
  (search-backward-regexp org-drawer-regexp nil nil count))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defhydra hydra-org-drawers (global-map "C-c n")
  "Move to next drawer."
  ("n" org-next-drawer)
  ("p" (lambda () (interactive) (org-next-drawer -1))))
#+END_SRC

** Convenient MozRepl Control
:PROPERTIES:
:ID:       b5a60402-65b7-45af-a8e4-43a8766b20b0
:END:

#+BEGIN_SRC emacs-lisp
(defhydra hydra-moz-controller (global-map "C-c z")
  "Use MozRepl."
  ("+" moz-controller-zoom-in)
  ("-" moz-controller-zoom-out)
  ("0" moz-controller-zoom-reset)
  ("R" moz-controller-page-refresh)
  ("b" moz-controller-tab-previous)
  ("f" moz-controller-tab-next)
  ("k" moz-controller-tab-close)
  ("l" moz-controller-get-current-url)
  ("n" moz-controller-page-down)
  ("p" moz-controller-page-up)
  ("u" moz-controller-view-page-source))
#+END_SRC

** Hide Lines in the Agenda                                             :org:
:PROPERTIES:
:ID:       260d148a-634d-48cf-b6d2-c35d811e97f4
:END:

Be able to hide a line of the org agenda.

This is functionality that affects only the representation in an
agenda buffer.

This function can be used to scan an agenda with the "scan to
nothing" technique.  Which is start at the top and hide each line
you have thought of.

#+BEGIN_SRC emacs-lisp
(defun mw-org-agenda-hide-line-or-region ()
  "Hide the line containing point or lines in the region from the agenda.
This action is just cosmetics in the agenda buffer and does not
affect the sources.  I.e. the lines appear again at the next
refresh for an agenda.

Note: This function has been derived from
`org-agenda-drag-line-forward'.

Note: Of course you can make the agenda buffer writable and use
some standard deletion functionality.  But you need to take the
action of making the agenda buffer writable.  And also take care
about some commands which might have a special meaning in the
agenda buffer e.g. C-k."
  (interactive)
  (let ((inhibit-read-only t))
    (if (region-active-p)
        (delete-region
         (save-excursion
           (goto-char (region-beginning))
           (beginning-of-line)
           (point))
         (progn
           (goto-char (region-end))
           (when (or (not (= (region-end)
                             (save-excursion
                               (goto-char (region-end))
                               (beginning-of-line)
                               (point))))
                     (= (point) (mark)))
             (forward-line))
           (point)))
      (move-beginning-of-line 1)
      (delete-region
       (point)
       (save-excursion (move-beginning-of-line 2) (point))))
    ;; (org-agenda-reapply-filters)
    ;; (org-agenda-mark-clocking-task)
    ))
#+END_SRC

*** Keybinding
:PROPERTIES:
:ID:       37660ab1-382f-4799-b0da-f92f0669b7dc
:END:

Using the key 'h' which reminds of hide.  'h' is the standard binding
to popup holidays, but they are still accessable on key 'H'.

#+BEGIN_SRC emacs-lisp
(eval-after-load "org-agenda"
  '(org-defkey org-agenda-mode-map (kbd "h") #'mw-org-agenda-hide-line-or-region))
#+END_SRC

** A key for Info-search-next                                          :info:

*** Example
:PROPERTIES:
:ID:       dd1212ef-947d-4277-b115-b62bf7890795
:END:

X wants to find "mysearchstring" muliple times.  It's possible already
by typing

s mysearchstring
s RET
s RET

With the key setting below the sequence above simplifies to

s mysearchstring
a
a

#+BEGIN_SRC emacs-lisp
(eval-after-load 'info
  '(progn (define-key Info-mode-map (kbd "a") #'Info-search-next)))
#+END_SRC

** Org Labs

*** property-action from agenda
:PROPERTIES:
:ID:       9ddca184-0601-4564-b43e-354619687119
:END:

#+BEGIN_SRC emacs-lisp
(org-defkey org-agenda-mode-map "\C-c\C-xy" #'org-agenda-property-action)
#+END_SRC

*** list items with a date
:PROPERTIES:
:ID:       be1be03d-f736-4990-9c12-f18d51cf93d4
:END:

#+BEGIN_SRC emacs-lisp
(defun org-list-insert-inactive-ts-item ()
  "Insert a list item starting with an inactive timestamp."
  (interactive)
  (let ((itemp (org-in-item-p)) (pos (point)))
    (when itemp
      (goto-char itemp)
      (let* ((struct (org-list-struct))
	     (prevs (org-list-prevs-alist struct))
	     (s (concat (with-temp-buffer
                          (org-insert-time-stamp nil t t)
                          (buffer-string)) " ")))
        (setq struct (org-list-insert-item pos struct prevs nil s))
        (org-list-write-struct struct (org-list-parents-alist struct))
        (looking-at org-list-full-item-re)
	(goto-char (match-end 0))
        (end-of-line)))))
#+END_SRC

*** org hide above first heading
:PROPERTIES:
:ID:       d6da5aa9-578e-4664-991e-2219adf59665
:END:

#+BEGIN_SRC emacs-lisp
(defun org-first-heading ()
  (goto-char (point-min))
  (if (re-search-forward (concat "^\\(" org-outline-regexp "\\)") nil t)
      (goto-char (match-beginning 0))))

(defun org-flag-region-before-first-heading (&optional show)
  (interactive "P")
  (goto-char (point-min))
  (outline-flag-region
   (point)
   (progn (org-first-heading) (point))
   (not show)))
#+END_SRC

*** org-show-context-detail
:PROPERTIES:
:ID:       4ce2db4c-b01c-430e-a811-6abb70dd7925
:END:

#+BEGIN_SRC emacs-lisp
(setq org-show-context-detail
      '((isearch . lineage)
        (bookmark-jump . lineage)
        (occur-tree . minimal)
        (default . ancestors)))
#+END_SRC

*** Agenda for deadlines only
:PROPERTIES:
:ID:       786a3036-7e15-42ae-be82-8904abb07ea5
:END:

#+BEGIN_SRC emacs-lisp
     (eval-after-load "org-agenda"
'(add-to-list 'org-agenda-custom-commands
             '("A" "Agenda; only deadlines"
               agenda ""
               ((org-agenda-entry-types '(:deadline))))))
#+END_SRC

Source:
http://emacs.stackexchange.com/questions/12930/display-org-todo-list-of-entries-with-deadlines
;;

*** Timetravel Org
:PROPERTIES:
:ID:       30abc2f7-9f3a-4f90-8402-4d0fbfe9904f
:END:

When you want to see or change something in the agenda at a
different day the following functions might be helpful.

This fun allows (afaict) the view on an Org agenda when setting an
other date as current.

#+BEGIN_SRC emacs-lisp
(defun mw-org-timemachine-set-other-today ()
  "Choose a day from the calendar as today for Org."
  (interactive)
  (setq org-extend-today-until
        (truncate (- (/ (org-time-stamp-to-now (org-read-date) t) 60 60)))))

(defun mw-org-timemachine-reset-today ()
  "Reset timetravel to zero."
  ;; For me it's okay, but maybe better reset to the original
  ;; value which might have been something.different from zero.
  (interactive)
  (setq org-extend-today-until 0))
#+END_SRC

*** org-todo with certain date
:PROPERTIES:
:ID:       690374f5-f4b8-4ee2-9325-3514acf8e242
:END:

recall: there is already org-todo-yesterday.

#+BEGIN_SRC emacs-lisp
(defun mw-org-todo-with-other-date (date &optional arg)
  "Like `org-todo' but ask for an other DATE.
Optional argument ARG prefix arg."
  (interactive (list (org-read-date) current-prefix-arg))
  (let* ((org-use-effective-time t)
         (hour
          (truncate
           (- (/ (org-time-stamp-to-now date t)
                 60 60))))
          (org-extend-today-until (1+ hour)))
    (org-todo arg)))
#+END_SRC

** Unset a Register
:PROPERTIES:
:ID:       fbe2c382-6db3-414c-94ee-870280ee9f2b
:END:

I think this functionality is not in Emacs core yet.

#+BEGIN_SRC emacs-lisp
(defun clear-register (register)
  "Unset contents of Emacs register named REGISTER."
  (interactive (list (register-read-with-preview "Clear register: ")))
  (setf register-alist (assq-delete-all register register-alist)))
#+END_SRC

** Controlled Garbage Collection
:PROPERTIES:
:ID:       486b2663-8cf1-48dc-85e8-a98312f01015
:END:

This is from
http://bling.github.io/blog/2016/01/18/why-are-you-changing-gc-cons-threshold/.

#+BEGIN_SRC emacs-lisp
(defun my-minibuffer-setup-hook ()
  (setq gc-cons-threshold most-positive-fixnum))

(defun my-minibuffer-exit-hook ()
  (setq gc-cons-threshold 800000))

(add-hook 'minibuffer-setup-hook #'my-minibuffer-setup-hook)
(add-hook 'minibuffer-exit-hook #'my-minibuffer-exit-hook)
#+END_SRC

** LOB
:PROPERTIES:
:ID:       9486fcf2-e34d-42ab-9dd6-3ea8013fb2f6
:END:

Library of Babel is a collection of Org source blocks.  This code is for adding my additions to the lob.

#+BEGIN_SRC emacs-lisp
(org-babel-lob-ingest "~/org/mw-lob.org")
#+END_SRC

** Switch buffers between frames
:PROPERTIES:
:ID:       92d781a8-abfb-4dc3-9213-cbd86e953f27
:END:

Found at [[http://www.emacswiki.org/emacs/SwitchingBuffers#toc5][EmacsWiki: Switching Buffers]] provided by YoniRabkinKatzenell
AFAICS.  I think this can be useful for me.

#+BEGIN_SRC emacs-lisp
(defun yrk-switch-buffers-between-frames ()
  "Switch the buffers between the two last frames."
  (interactive)
  (let ((this-frame-buffer nil)
        (other-frame-buffer nil))
    (setq this-frame-buffer (car (frame-parameter nil 'buffer-list)))
    (other-frame 1)
    (setq other-frame-buffer (car (frame-parameter nil 'buffer-list)))
    (switch-to-buffer this-frame-buffer)
    (other-frame 1)
    (switch-to-buffer other-frame-buffer)))
#+END_SRC

** VCS

***** This is a Typical Procedere with Commit Message for the Author
:PROPERTIES:
:ID:       94bdf8f2-7dba-4272-bf05-a6ec42efc1f8
:END:

Automate the typical thing and get happy.  ^_^

#+BEGIN_SRC emacs-lisp
(defun mw-dtrt-commit-msg-prepare()
  "This function applied to a commit-msg buffer shall dtrt."
  (interactive)
  (let ((beg (point)))
    (search-forward-regexp "modified: *")
    (delete-region beg (point)))
  (end-of-line)
  (let ((end (point)))
    (search-backward-regexp "\\.")
    (delete-region (point) end))
  (insert ":\n")
  (backward-char))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-hook 'git-commit-mode-hook
          (lambda () (key-chord-define-local "p8" #'mw-dtrt-commit-msg-prepare)))
#+END_SRC

** linum experiments                                                 :linum:
:PROPERTIES:
:ID:       64fe7c5b-7cb8-4d93-bee4-416b7b7358c0
:END:

#+BEGIN_SRC emacs-lisp
(defun delta (line pointline)
  "LINE is the processed line.
POINTLINE is the line containing point."
  (format "%d" (- line pointline)))

(defun delta5 (line pointline)
  "LINE is the processed line.
POINTLINE is the line containing point."
  (format "%5d" (- line pointline)))

(defun the-line (line)
  "LINE is the processed line.
pointline is the line containing point."
  (format "%4d" line))

;; (setq linum-format 'the-line)
;; (setq linum-format 'delta5)
#+END_SRC

** Toggle-letter-case
:PROPERTIES:
:ID:       b42a6e0d-0a8c-4575-a3b5-1464961792fe
:END:

#+BEGIN_SRC emacs-lisp
;; http://www.star.bris.ac.uk/bjm/emacs-tips.html#sec-1-14

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; change case of letters                                                 ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; http://ergoemacs.org/emacs/modernization_upcase-word.html
(defun toggle-letter-case ()
  "Toggle the letter case of current word or text selection.
Toggles between: “all lower”, “Init Caps”, “ALL CAPS”."
  (interactive)
  (let (p1 p2 (deactivate-mark nil) (case-fold-search nil))
    (if (region-active-p)
        (setq p1 (region-beginning) p2 (region-end))
      (let ((bds (or (bounds-of-thing-at-point 'word)
                     (progn (forward-whitespace 1)
                            (bounds-of-thing-at-point 'word)))))
        (setq p1 (car bds) p2 (cdr bds))))
    (when (not (eq last-command this-command))
      (save-excursion
        (goto-char p1)
        (cond
         ((looking-at "[[:lower:]][[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]][[:upper:]]") (put this-command 'state "all caps"))
         ((looking-at "[[:upper:]][[:lower:]]") (put this-command 'state "init caps"))
         ((looking-at "[[:lower:]]") (put this-command 'state "all lower"))
         ((looking-at "[[:upper:]]") (put this-command 'state "all caps"))
         (t (put this-command 'state "all lower")))))
    (cond
     ((string= "all lower" (get this-command 'state))
      (upcase-initials-region p1 p2) (put this-command 'state "init caps"))
     ((string= "init caps" (get this-command 'state))
      (upcase-region p1 p2) (put this-command 'state "all caps"))
     ((string= "all caps" (get this-command 'state))
      (downcase-region p1 p2) (put this-command 'state "all lower")))))

;;set this to M-c
(global-set-key "\M-C" #'toggle-letter-case)
#+END_SRC

** ispell and org
:PROPERTIES:
:ID:       91013af9-c3c6-44b9-a4e9-42ea23f495da
:END:

[[gnus:nntp+news.gwene.org:gwene.org.emacsen.planet#x1-OJQzcaDHUGvOvCmRSA6fSHKcoWE@gwene.org][Email from Artur Malabarba: Endless Parentheses: Making Is]]

Subject: Endless Parentheses: Making Ispell work with org-mode
Newsgroups: gwene.org.emacsen.planet
Date: Mon, 24 Aug 2015 02:00:00 +0200 (15 hours, 49 minutes, 21 seconds ago)
Archived-at: <http://endlessparentheses.com/ispell-and-org-mode.html?source=rss>

[1. text/html]

If you’ve every tried to do some spell-checking in org-mode you know
how finicky that can be. Ispell is happy to

check absolutely anything, even code blocks and property drawers! When
you’re blogging about code-snippets from an org file this annoyance
quickly turns into irritation. Here’s how you fix it.

#+BEGIN_SRC emacs-lisp
(defun endless/org-ispell ()
  "Configure `ispell-skip-region-alist' for `org-mode'."
  (make-local-variable 'ispell-skip-region-alist)
  (add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
  (add-to-list 'ispell-skip-region-alist '("~" "~"))
  (add-to-list 'ispell-skip-region-alist '("=" "="))
  (add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC" . "^#\\+END_SRC")))
(add-hook 'org-mode-hook #'endless/org-ispell)
#+END_SRC

** ediff
:PROPERTIES:
:ID:       95a7af9e-1050-461b-8324-96fc103d15c3
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'ediff-keymap-setup-hook
          (lambda ()
            (define-key
              ediff-mode-map "8"
              #'mw-ediff-set-visible-mode-in-ediff-buffers)))
#+END_SRC

** Drag windows
:PROPERTIES:
:ID:       f83d1053-b269-4647-ac28-085493f17bd2
:END:

Found [2015-03-03 Tue 17:18]
Link: https://tsdh.wordpress.com/2015/03/03/swapping-emacs-windows-using-dragndrop/

When using Emacs on a larger screen where Emacs’ frame is split
into multiple windows, you sometimes wish there was some simple way
to rearrange which buffer is shown in which window. Of course, you
can do that by moving through your windows and using
switch-to-buffer and friends but that’s not really convenient.

So here’s a command which lets you use drag one buffer from one
window to the other. The effect is that the buffers of the start
and target window are swapped.

#+BEGIN_SRC emacs-lisp
(defun th/swap-window-buffers-by-dnd (drag-event)
  "Swaps the buffers displayed in the DRAG-EVENT's start and end window."

  (interactive "e")
  (let ((start-win (cl-caadr drag-event))
        (end-win   (cl-caaddr drag-event)))
    (when (and (windowp start-win)
               (windowp end-win)
               (not (eq start-win end-win))
               (not (memq (minibuffer-window)
                          (list start-win end-win))))
      (let ((bs (window-buffer start-win))
            (be (window-buffer end-win)))
        (unless (eq bs be)
          (set-window-buffer start-win be)
          (set-window-buffer end-win bs))))))
#+END_SRC

Bind it to some mouse drag event and have fun. For example, I use

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<C-S-drag-mouse-1>") #'th/swap-window-buffers-by-dnd)
#+END_SRC

So that drag’n’drop with the left mouse button and control and shift
pressed is bound to the command above.


** Pomodoro
:PROPERTIES:
:ID:       5fae4b2e-b6dc-4193-b0c4-bca7b5c87c71
:END:

Support the famous tomato-technique.  The idea is to work
concentrated for a while (tomato) and then take a break.  This shall
be repeated some times a day.

The functions here support pomodoro based on org.

Source: http://www.couchet.org/blog/index.php?post/2010/08/04/Pomodoro-et-org-mode
Author there: Frédéric Couchet le mercredi, août 4 2010, 22:53

#+BEGIN_SRC emacs-lisp
;;; (add-to-list 'org-modules 'org-timer) ;; done via customize

(require 'org-timer)
(defvar *mw-pomodoros-completed-in-session* 0
  "Number of pomodoros in the current emacs-session.")

(defvar *mw-pomodoros-before-longer-break* 3
  "Number of pomodoros to reach for a longer break.")

(defcustom *mw-pomodoro-pause-duration* 3
  "Duration in minutes of standard pauses between pomodoros.")

(defcustom *mw-pomodoro-longer-pause-duration* 15
  "Duration in minutes of standard pauses between pomodoros.")

(setq org-timer-default-timer "25")
(add-hook 'org-clock-in-hook
          '(lambda ()
             (if (not ;org-timer-timer-is-countdown ; 201501151654 maint
                  org-timer-countdown-timer)
                 (progn
                   (message "Start a fresh timer.")
                   (org-timer-set-timer '(64))))))
(add-hook 'org-clock-out-hook
          '(lambda ()
             (setq org-mode-line-string nil)))

(defun mw-bring-hanoi-buffer-into-view-mode ()
  (with-current-buffer (get-buffer-create "*Hanoi*")
    (special-mode)))

;; disable org's standard notification [2016-03-17 Thu 10:32] TODO
;; improve and go into the details...
(setf org-show-notification-handler #'ignore)

(setq mw-org-pause-state nil) ; TODO: make mw-org-pause-state more locally, please!
(defun mw-org-pause-state ()
  "Diplay `mw-org-pause-state-show'."
  (interactive)
  (message "%s mw-org-pause-state" mw-org-pause-state))

(add-hook
 'org-timer-done-hook
 '(lambda ()
    (if mw-org-pause-state
        (progn
          (setq mw-org-pause-state nil)
          (message "Pause over at %s.  What about another tomato?"
                   (format-time-string "%T"))
          (start-process "play-a-sound" "*play-a-sound-output*"
                         "mplayer" (expand-file-name
                                    "~/media/sound/technical/aoogah.wav"))
                                        ;(play-sound '(sound :file
                                        ;".../aoogah.wav")) ;
                                        ;[2014-06-02 Mon 15:14] this
                                        ;line played the sound also.
                                        ;But sychronously.
          ;; (zone)
          )
      (progn
        (setq *mw-pomodoros-completed-in-session*
              (1+ *mw-pomodoros-completed-in-session*))
        (org-clock-goto)
        ;; going to an org buffer is necessary for starting
        ;; an org timer.
        (mw-org-trigger-timer-for-pause
         (if (= 0 (% *mw-pomodoros-completed-in-session*
                     *mw-pomodoros-before-longer-break*))
             *mw-pomodoro-longer-pause-duration*
           *mw-pomodoro-pause-duration*))
        (message
         "Tomato done at %s.  Il est vraiment temps de prendre une pause."
         (format-time-string "%T"))
        ;; (start-process "play-a-sound" "*play-a-sound-output*"
        ;;                "mplayer" (expand-file-name "~/media/sound/human/shutdown.wav"))
        (start-process "play-a-sound" "*play-a-sound-output*"
                       "espeak"
                       "-v"
                       ;; "en-swedish"
                       "en"
                       "-s"
                       "125" ;; word speed
                       "The tomato rings.  Take a rest, now, please.")
        (zone-nyan-preview)))))

(defun mw-org-trigger-timer-for-pause (&optional duration)
  "Start a timer for a pause of `DURATION' minutes.

   `DURATION' defaults to 5.  See hook `org-timer-done-hook' for
   actions at timers end.

     It looks to me that the org-timer thing is broken.  I can't set
   a new timer with org-timer-set-timer from an org-buffer any
   more except with the triple universal prefix AKA '(64).

   [2014-06-27 Fri 11:12] Good news: I could use M-x
   org-timer-set-timer today and it did the expected thing."
  (interactive)
  (if (derived-mode-p 'org-mode)
      (let ((saved-org-timer-default-timer org-timer-default-timer)
            (duration (if (not duration) *mw-pomodoro-pause-duration*
                        (number-to-string duration))))
        (setq org-timer-default-timer duration)
        (org-timer-set-timer '(64))
        (setq org-timer-default-timer saved-org-timer-default-timer)
        (setq mw-org-pause-state t))
    (error "mw-org-trigger-timer-for-pause: Not in an Org buffer")))
#+END_SRC


** navi-mode
:PROPERTIES:
:ID:       6b809606-6e13-438a-84f6-0a07c1519fb8
:END:

Recall function [[help:navi-search-and-switch][navi-search-and-switch]] to activate a navi-buffer.

#+BEGIN_SRC emacs-lisp
;(require 'navi-mode)
#+END_SRC

** Quickly access dict.leo.org                                 :weak:
:PROPERTIES:
:ID:       29eb9c88-24c3-4159-b51f-ea597b9523ab
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-ask-leo-about-word-at-point ()
  "Call leo word engine using w3m."
  (interactive)
  (w3m-search "leo" (thing-at-point 'word)))

(defun mw-ask-leo (arg)
  "Call leo word engine using w3m."
  (interactive "sWord: ")
  (kill-new arg)
  (w3m-search "leo" arg))
#+END_SRC

** Translate via web-leo

(defun mw-eww-ask-leo-fr (arg)
  (interactive "sWord: ")
  (eww (format "http://pda.leo.org/?lp=frde&search=%s&searchLoc=0&resultOrder=basic&multiwordShowSingle=on" arg)))

(defun mw-eww-ask-leo-fr-region (start end)
  (interactive "r")
  (eww
   (format
    "http://pda.leo.org/?lp=frde&search=%s&searchLoc=0&resultOrder=basic&multiwordShowSingle=on"
    (buffer-substring start end ))))

(defun mw-eww-ask-leo-en (arg)
  (interactive "sWord: ")
  (eww (format "http://pda.leo.org/?lp=ende&search=%s&searchLoc=0&resultOrder=basic&multiwordShowSingle=on" arg)))

** Rope Read to save eye-movements
:PROPERTIES:
:ID:       2c64db40-7503-4c19-a245-2686d6759164
:END:

Most important package!  Save eye movements!
Use via package manager to test if it's okay.

#+BEGIN_SRC emacs-lisp
;; local dev version:
;; (push "~/p/elisp/mw/rope-read-mode" load-path)
;; (require 'rope-read-mode)
(use-package rope-read-mode
  :config
  (progn
    (define-key rope-read-mode-map "d" #'rope-read-next-paragraph)))

;; (define-key rope-read-mode-map "d" 'rope-read-reol) ;; start from current line with rope-read
;; (define-key rope-read-mode-map "r" 'rope-read-delete-overlays)
#+END_SRC

** Convenient snapshot of emacs from within
:PROPERTIES:
:ID:       236c5b50-a3b6-4c02-a40f-96101519d184
:END:

#+BEGIN_SRC emacs-lisp
(push "~/p/elisp/mw/emacsshot" load-path)
(require 'emacsshot)
(global-set-key
 [print] ; (kbd "<print>")
 (lambda (&optional prefix)
   (interactive "p")
   (case prefix
     (1 (emacsshot-snap-window))
     (4 (emacsshot-snap-frame))
     (16 (emacsshot-snap-window-include-modeline)))))
#+END_SRC

** Hippie expand
:PROPERTIES:
:ID:       858cfba2-7bb2-48a2-9ec1-d3cc037840ef
:END:

Hippie expand is using various sources as potential for expansion.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-/") 'hippie-expand)
#+END_SRC

** Special holidays
:PROPERTIES:
:ID:       2a68711a-fb74-45cc-9ac5-145c2758f971
:END:

Special Holidays can be defined in a function.  Hooking can be done
via variable `holiday-other-holidays'.

Note: The code here looks not so good.  Improvement would be good.

#+BEGIN_SRC emacs-lisp
(defun mw-further-holidays-of-interest ()
  "For specifying further holidays.
This function can be stored in variable `holiday-other-holidays'
for an effect."
  (if (= 2014 displayed-year)
      (if (or (= 4 displayed-month) (= 5 displayed-month) (= 6 displayed-month))
          '(((5 29 2014) "Christi Himmelfahrt"))
        (if (or (= 7 displayed-month) (= 8 displayed-month) (= 9 displayed-month))
            '(((8 15 2014) "Mariä Himmelfahrt"))))
    (if (= 2016 displayed-year)
        (if (or (= 4 displayed-month) (= 5 displayed-month) (= 6 displayed-month))
            '(((5 5 2016) "Christi Himmelfahrt"))
          (if (or (= 7 displayed-month) (= 8 displayed-month) (= 9 displayed-month))
              '(((8 15 2016) "Mariä Himmelfahrt")))))))
#+END_SRC

** Switch sound on/off
:PROPERTIES:
:ID:       07d4ced5-486f-448f-9d47-74f6023a0c2f
:END:

[2017-03-22 Wed 13:00] When calling the sound goes to 0%!
#+BEGIN_SRC emacs-lisp
(defun mw-sound-100% ()
  "Pull all rulers in the amixer to 100%."
  (interactive)
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Master" "64")
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Speaker" "64" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Headphone" "64" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "PCM" "255" )
  (message "sound set to 100%%"))

(defun mw-sound-set-enjoyable-volume ()
  "Enjoyable volume for listening with headphones.

  The effect of this function is somewhat subjective."
  (interactive)
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Master" "0")
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Speaker" "64" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Headphone" "64" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "PCM" "255" )
  (message "personal sound level set"))

(defun mw-sound-0% ()
  "Pull all rulers in the amixer to 0 ."
  (interactive)
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Master" "0")
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Speaker" "0" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "Headphone" "0" )
  (start-process "" "*mw-amixer*"
                 "amixer" "set" "PCM" "0" )
  (message "sound set to 0%%"))
#+END_SRC

** Personalize the sound of the bell
:PROPERTIES:
:ID:       f5e3d91a-1137-4640-b453-96c64eba2d16
:END:

Bird sound is awesome.  In particular when the sound plays
concurrently.

#+BEGIN_SRC emacs-lisp
(defun mw-play-little-bird-sound ()
  "Play a little bird sound."
  (interactive)
  (start-process
   "play-a-sound" "*play-a-sound-output*"
   "mplayer" "-af" "volume=-15"
   (expand-file-name "~/media/sound/birds/Tufted-Tit-Mouse-web-II.wav")))
(setq ring-bell-function 'mw-play-little-bird-sound)
;; turn off with: (setq ring-bell-function 'ignore)
#+END_SRC

** ill an url at point
:PROPERTIES:
:ID:       e8a974e9-b453-41ab-88c7-c7878ef79a11
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-kill-url-at-point ()
  "Try to interpret the thing at point as url and if so put to kill ring."
  (interactive)
  (kill-new (thing-at-point 'url)))
(global-set-key (kbd "C-c M-w") 'mw-kill-url-at-point)
#+END_SRC

** Duplicate a w3m-session
:PROPERTIES:
:ID:       75b8c4c4-eb78-405a-9594-70c94d0c6b68
:END:

- [2014-07-18 Fri 17:14] It looks like the defun below is already
  there in w3m: "M-n runs the command w3m-copy-buffer."

#+BEGIN_SRC emacs-lisp
(defun mw-w3m-duplicate-session (&optional reload)
  "Duplicate the w3m-session.
Optional argument RELOAD for w3m-view-this-url-1."
  (interactive "P")
  (if (not (eq major-mode 'w3m-mode))
      (message "This command applies resonably to w3m mode only")
    (if w3m-current-url
        (w3m-view-this-url-1 w3m-current-url reload 'new-session)
      (message "No current URL"))))
#+END_SRC

** wcheck
:PROPERTIES:
:ID:       550a98a3-e82b-4bec-80d5-f56b2b042ee8
:END:

wcheck is a mode for checking things in a buffer.  Might be worth to
invest some energy into its configuration for spell checking.

There is documentation on https://github.com/tlikonen/wcheck-mode.

I found out about wcheck's existance when reading an emacs group.

The following example shows that wcheck can be used for indication of
trailing whitespace.

#+BEGIN_SRC emacs-lisp
;; source: https://github.com/tlikonen/wcheck-mode
(setq wcheck-language-data
      '(("Trailing whitespace"
	 (program . identity)
	 (action-program . (lambda (marked-text)
			     (list (cons "Remove whitespace" ""))))
	 (face . highlight)
	 (regexp-start . "")
	 (regexp-body . "[ \t]+")
	 (regexp-end . "$")
	 (regexp-discard . "")
	 (read-or-skip-faces
	  (nil)))))
#+END_SRC

** Additions around eww

*** Switch from w3m to eww and vice versa
:PROPERTIES:
:ID:       613121b1-9af0-4815-8120-ac236527cc30
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-w3m-switch-to-eww ()
  "Switch to eww from w3m."
  (interactive)
  (eww w3m-current-url))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun mw-eww-switch-to-w3m ()
  "Switch to w3m from eww."
  (interactive)
  (w3m (eww-current-url)))
#+END_SRC

*** Duplicate eww buffer
:PROPERTIES:
:ID:       48c2f799-f29f-477b-903d-114dc89ca484
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-eww-duplicate-buffer ()
  "Create a further eww buffer for current url."
  (interactive)
  (when (eq major-mode 'eww-mode)
    (eww-browse-url (plist-get eww-data :url) t)))
#+END_SRC

*** Rename Current Page
:PROPERTIES:
:ID:       0524e938-4baf-4552-a999-c3cafce51c14
:END:

This is for somehow saving the page to not loosing it at the next eww
call.

#+BEGIN_SRC emacs-lisp
(require 'eww)
(if (boundp 'eww-mode-map)
    (progn
      (define-key eww-mode-map "x" #'mw-eww-duplicate-buffer) ;'rename-uniquely
      (message "Added 'x' in eww-mode-map.")
      (define-key eww-mode-map "f" #'eww-open-ff-page)
      (message "Added 'x' in eww-mode-map."))
  (message
   (concat
    "FAILED adding 'x' to eww-mode-map."
    "  REASON: eww-mode-map is not bound yet.")))
#+END_SRC

*** eww on region
:PROPERTIES:
:ID:       96c018f3-33b7-451f-974e-aba9dfdf12e0
:END:

eww

#+BEGIN_SRC emacs-lisp
(defun mw-eww-trigger-with-region-text ()
  "Trigger eww with current region as input."
  (interactive)
  (eww (buffer-substring
        (region-beginning)
        (region-end))))
(defalias 'mw-eww-on-region 'mw-eww-trigger-with-region-text
  "Shorter name.")
#+END_SRC

** Open url at point in firefox

#BEGIN_SRC emacs-lisp
(defun mw-browse-url-at-point-firefox ()
  (interactive)
  (let ((browse-url-browser-function #'browse-url-firefox))
    (browse-url-at-point)))
#+END_SRC

Also consider to call `browse-url-firefox' directly.

** Hidden mode line
:PROPERTIES:
:ID:       54610295-83bb-4d71-b7f7-2a04e19ebd04
:END:

Found the following mode line hiding function at
http://bzg.fr/emacs-hide-mode-line.html.  (Bastien)

#+BEGIN_SRC emacs-lisp
(defvar-local hidden-mode-line-mode nil)

(define-minor-mode hidden-mode-line-mode
  "Minor mode to hide the mode-line in the current buffer."
  :init-value nil
  :global t
  :variable hidden-mode-line-mode
  :group 'editing-basics
  (if hidden-mode-line-mode
      (setq hide-mode-line mode-line-format
            mode-line-format nil)
    (setq mode-line-format hide-mode-line
          hide-mode-line nil))
  (force-mode-line-update)
  ;; Apparently force-mode-line-update is not always enough to
  ;; redisplay the mode-line
  (redraw-display)
  (when (and (called-interactively-p 'interactive)
             hidden-mode-line-mode)
    (run-with-idle-timer
     0 nil 'message
     (concat "Hidden Mode Line Mode enabled.  "
             "Use M-x hidden-mode-line-mode to make the mode-line appear."))))

;; If you want to hide the mode-line in every buffer by default
;; (add-hook 'after-change-major-mode-hook 'hidden-mode-line-mode)

(defun mw-hidden-mode-line-for-all ()
  (interactive)
  (dolist (buffer (buffer-list))
    (set-buffer buffer)
    (unless hidden-mode-line-mode
      (hidden-mode-line-mode))))

(defun mw-hidden-mode-line-deactivate-for-all ()
  (interactive)
  (dolist (buffer (buffer-list))
    (set-buffer buffer)
    (when hidden-mode-line-mode
      (hidden-mode-line-mode))))
#+END_SRC

** Strip
:PROPERTIES:
:ID:       13bcd1d1-39a9-423c-813a-b26ba46ffbab
:END:

Go further from hidden-mode-line-mode.

#+BEGIN_SRC emacs-lisp
(defun mw-strip ()
  "Strip window and frame."
  (interactive)
  (hidden-mode-line-mode)
  (when hidden-mode-line-mode
    (fringe-mode 0)
    (scroll-bar-mode -1)))
#+END_SRC

** Key sequences to open browser
:PROPERTIES:
:ID:       9bf0ae82-8fcc-4b7f-8309-964e731ffb89
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "\C-cg") 'eww)
(global-set-key (kbd "\C-cG") 'browse-url)
(global-set-key (kbd "\C-cF") 'browse-url-firefox)
#+END_SRC

** mpages
:PROPERTIES:
:ID:       cc89df5d-a0f8-4b36-aaff-9939161f5c5d
:END:

Using a local branch and not the package to test a version with
encryption.

#+BEGIN_SRC emacs-lisp
(push  "~/p/elisp/mw/mpages" load-path)
(autoload 'mpages "mpages" "For writing morning pages." t nil)

(defadvice mpages (after ctrlc-ctrlc-to-finish activate)
  "Set C-c C-c to close the mpage writing.
Set the key for encrytion, then save and kill the buffer.
This binding shall make the close more convenient."
  (local-set-key [?\C-c ?\C-c] (lambda ()
                                 (interactive)
                                 (setq epa-file-encrypt-to '("49010A040A3AE6F2"))
                                 (save-buffer)
                                 (kill-buffer))))
#+END_SRC

** dired-x
:PROPERTIES:
:ID:       50e7e452-65c7-4153-97b0-84db4413bb1e
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'dired-load-hook
          (lambda ()
            (load "dired-x")
            ;; Set dired-x global variables here.  For example:
            ;; (setq dired-guess-shell-gnutar "gtar")
            ;; (setq dired-x-hands-off-my-keys nil)
            ))
#+END_SRC

** from dired to ediff
:PROPERTIES:
:ID:       afbf5575-7fac-4e9f-a71c-b644c19c77ab
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'dired-mode-hook
          (lambda ()
            (define-key dired-mode-map "E" #'dired-ediff)))

(defun dired-ediff ()
  "Run ediff on the files at point and mark from dired."
  (interactive)
  (let
      ((file (dired-get-filename t))
       (other (if (and transient-mark-mode mark-active)
                  (save-excursion (goto-char (mark t))
                                  (dired-get-filename t t)))))
    (when (and file other (not (equal file other)))
      (ediff file other))))
#+END_SRC

** from diff to ediff
:PROPERTIES:
:ID:       ec3fdb80-6d3f-486f-bdbe-c4bb0304aad3
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'diff-mode-hook (lambda () (define-key diff-mode-map "E" #'mw-diff-ediff)))

(defun mw-diff-ediff ()
  "Run ediff for the diff at point."
  (interactive)
  (ediff
   (diff-find-file-name nil nil)
   (diff-find-file-name t nil)))
#+END_SRC

** eww on file in dired
:PROPERTIES:
:ID:       e1525a65-3612-431e-b903-4da4f7f0dd3f
:END:

Setting key e for opening the file at point in eww.  Note there is
already key W for opening the file at point in some browser.

#+BEGIN_SRC emacs-lisp
(add-hook 'dired-mode-hook
          (lambda ()
            ;; Set dired-x buffer-local variables here.  For example:
            ;; (dired-omit-mode 1)
            ;;
            ;; lab: "e" for open the file in eww.  Note: I never used
            ;; "e" to start edit a file of a dired (which is the
            ;; default behavior. [2016-07-21 Thu 17:11])
            (define-key dired-mode-map "e"
              (lambda () (interactive)
                (eww-open-file (dired-get-file-for-visit))))))

;; (setf dired-mode-hook nil)
#+END_SRC

** Delete blank lines also above
:PROPERTIES:
:ID:       adfb87e8-132c-4e68-a2a7-76c8fb25f39c
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key  (kbd "C-x C-o") #'mw-delete-blank-lines)
#+END_SRC

[2015-07-13 Mon 11:54] Activation.  Let's see if the removal of the
blank lines above proves useful.

** Disable query about active processes at quit
:PROPERTIES:
:ID:       94d56b20-f316-40a5-9c9b-b0935a17a2d1
:END:

#+BEGIN_SRC emacs-lisp
(require 'cl)
(defadvice save-buffers-kill-emacs (around no-query-kill-emacs activate)
           (cl-flet ((process-list ())) ad-do-it))
#+END_SRC

Source: [[http://timothypratley.blogspot.de/2015/07/seven-specialty-emacs-settings-with-big.html][Programming: Seven specialty Emacs settings with big payoffs]].

** Open line below
:PROPERTIES:
:ID:       26da7498-cddb-4ece-8abd-764893ddda36
:END:

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-S-o") #'mw-open-line-below)
(global-set-key (kbd "C-S-a") #'mw-open-line-above)
#+END_SRC

** Real delete
:PROPERTIES:
:ID:       2ff4a92f-b510-4fcd-a17e-6cd70f3c5da5
:END:

Real delete of region, not this 'play it save and put the delete into
kill-ring' stuff.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "\C-cw") #'delete-region)
#+END_SRC

*** TODO Test this                                                 :noexport:

** Mouse Avoidance
:PROPERTIES:
:ID:       ddb352a3-a10c-4e13-a54b-6b7553522d25
:END:

Documentation says
#+BEGIN_QUOTE
Should be one of the symbols ‘banish’, ‘exile’, ‘jump’, ‘animate’,
‘cat-and-mouse’, ‘proteus’, or ‘none’.
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(mouse-avoidance-mode 'proteus)
#+END_SRC

** Delete trailing ws on save
:PROPERTIES:
:ID:       94ffe130-b09b-4a67-ae99-0bbbe5172ddb
:END:

This is thought to keep the files cleaner.  This is thought to need
no more thought about trailing whitespace.

#+BEGIN_SRC emacs-lisp
(push
 (lambda ()
   (delete-trailing-whitespace))
 before-save-hook)

;; More care taken at first.  Ws cleanup only for a few modes:
;; (push
;;  (lambda ()
;;    (if (or (eq major-mode 'org-mode)
;;            (eq major-mode 'ledger-mode))
;;        (delete-trailing-whitespace)))
;;  before-save-hook)
#+END_SRC

** Enable more Emacs features
:PROPERTIES:
:ID:       6d9446c2-447f-4a92-9873-a9ec8a186eb7
:END:

Enable features that are disabled by default.

#+BEGIN_SRC emacs-lisp
(put 'narrow-to-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'scroll-left 'disabled nil)
(put 'narrow-to-page 'disabled nil)
(put 'downcase-region 'disabled nil)
(put 'dired-find-alternate-file 'disabled nil)
(put 'set-goal-column 'disabled nil)
(put 'erase-buffer 'disabled nil)
#+END_SRC

** Abbrevs
:PROPERTIES:
:ID:       7a5f0b0f-567a-4482-aa1d-889841fc5498
:END:

Started with the suggestion about abbreviations on
http://www.star.bris.ac.uk/bjm/emacs-tips.html#sec-1-19.

#+BEGIN_SRC emacs-lisp
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; abbreviations                                                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(setq-default abbrev-mode t)     ;; enable abbreviations
(setq save-abbrevs t)            ;; save abbreviations upon exiting xemacs
;; abbrev-file-name ; using the default setting.
(quietly-read-abbrev-file)       ;; reads the abbreviations file on startup
#+END_SRC

** Appointments from Org
:PROPERTIES:
:ID:       59b215f3-bfd9-4a7e-bd2a-96f5d1fef14d
:END:

Take into account the appointments for today from the org-agenda.
Note that this is done for the current org-agenda files.

Activate the appointment checking.

#+BEGIN_SRC emacs-lisp
(appt-activate 1)
#+END_SRC

See also [[id:f5e3d91a-1137-4640-b453-96c64eba2d16][Personalize the sound of the bell]] for the configuration of
the respective audio signal.

** Battery
:PROPERTIES:
:ID:       c3a8b888-a846-4c9a-ac43-cf96e53292f1
:END:

#+BEGIN_SRC emacs-lisp
(display-battery-mode)
#+END_SRC

** Beautification

*** Elisp
:PROPERTIES:
:ID:       1b2358a9-59b6-40cc-8698-f5b841870714
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook
          (lambda ()
            (setq-local prettify-symbols-alist
                        '(("lambda" . ?λ)))
            (prettify-symbols-mode 1)))
#+END_SRC

*** Python
:PROPERTIES:
:ID:       5c5e7b4a-c459-44c0-91c0-8490ae64f7cd
:END:

[[gnus:nntp+news.aioe.org:gnu.emacs.help#mailman.17951.1421331793.1147.help-gnu-emacs@gnu.org][Email from Stefan Monnier: Re: can emacs do this]]

#+BEGIN_SRC emacs-lisp
(add-hook 'python-mode-hook
          (lambda ()
            (setq-local prettify-symbols-alist
                        '(("lambda" . ?λ)
                          ("math.sqrt" . ?√)
                          ("math.pi" . ?π)
                          ("sum" . ?Σ)))
            (prettify-symbols-mode 1)))
#+END_SRC

** Natural Language Environment
:PROPERTIES:
:ID:       fc702171-43b8-4815-b911-40df2d9d37bf
:END:

Convenient switching of the input-method and the spell-checking.

This code is derived from http://www.emacswiki.org/emacs/FlySpell

#+BEGIN_SRC emacs-lisp
(defvar mw-lang-inputmethod-ring)

(let ((langs-inputmethods '(("deutsch" "german-prefix") ("american" nil))))
  (setq mw-lang-inputmethod-ring (make-ring (length langs-inputmethods)))
  (dolist (elem langs-inputmethods)
    (ring-insert mw-lang-inputmethod-ring elem)))

(defun cycle-ispell-language-and-input-method ()
  "Use the next language setting from mw-langs-inputmethod-ring."
  (interactive)
  (let ((lang-inputmethod (ring-ref mw-lang-inputmethod-ring -1)))
    (ring-insert mw-lang-inputmethod-ring lang-inputmethod)
    (ispell-change-dictionary (car lang-inputmethod))
    (set-input-method (cadr lang-inputmethod))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; [2014-07-08 Tue 11:34] Idea: one could also switch the completer
;; dictionary on M-tab.  (setq ispell-complete-word-dict
;; "/usr/share/dict/ngerman")

(let ((the-dicts '("/usr/share/dict/ngerman"
                   "/usr/share/dict/french"
                   "/usr/share/dict/words")))
  (setq mw-dict-ring (make-ring (length the-dicts)))
  (dolist (elem the-dicts) (ring-insert mw-dict-ring elem)))

(defun mw-cycle-ispell-completion-dict ()
  (interactive)
  (let ((dict (ring-ref mw-dict-ring -1)))
    (ring-insert mw-dict-ring dict)
    (setq ispell-alternate-dictionary  ;; ISSUE: which of these variables
          ;; ispell-complete-word-dict ;; should be taken here?
          dict)
    (message (concat dict " set for ispell completion."))))
#+END_SRC

** Scroll-Lock-Mode
:PROPERTIES:
:ID:       53615d33-2c09-4563-8476-0b385a8fc2d6
:END:

Scroll lock mode gives another buffer movement feeling.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<Scroll_Lock>") 'scroll-lock-mode)
#+END_SRC

** Rotate windows
:PROPERTIES:
:ID:       30f174db-4c99-445a-bc67-c2fef0b30b94
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-rotate-split ()
  "Somehow rotate buffers in the emacs-window.

Originates from gnu.emacs.help group 2006."
  (interactive)
  (let ((root (car (window-tree))))
    (if (listp root)
	(let* ((w1 (nth 2 root))
	       (w2 (nth 3 root))
	       (b1 (window-buffer w1))
	       (b2 (window-buffer w2)))
	  (cond ((car root)
		 (delete-window w2)
		 (set-window-buffer (split-window-horizontally) b2))
		(t
		 (delete-window w1)
		 (set-window-buffer (split-window-vertically) b1))))
      (message "Root window not split"))))
#+END_SRC

** Screen
:PROPERTIES:
:ID:       4bf02c92-06c4-4ca2-aa65-dcc906528f63
:END:

Seamless exchange with screen.

#+BEGIN_SRC emacs-lisp
(defvar mw-screen-exchange-filename
  "/tmp/screen-exchange"
  "Name of the file used by screen copy and paste.")
#+END_SRC

*** Screen like commands for slurp and write
:PROPERTIES:
:ID:       6499898f-fec7-4123-8d85-83cc1bde1f04
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-screen-exchange-slurp-insert ()
  (interactive)
  (insert-file-contents mw-screen-exchange-filename))

(defun mw-screen-exchange-write-region (start end)
  (interactive "r")
  (write-region start end mw-screen-exchange-filename))
#+END_SRC

*** Editing the screen-exchange file
:PROPERTIES:
:ID:       f5354f6b-9262-44a4-841c-71902283a01a
:END:

#+BEGIN_SRC emacs-lisp
(defun mw-screen-exchange-open-buffer ()
  "Open the screen exchange file in auto revert mode."
  (interactive)
  (set-buffer (find-file mw-screen-exchange-filename))
  (auto-revert-mode))
#+END_SRC

** Timeclock
:PROPERTIES:
:ID:       70d4f852-9ef0-4ed8-828d-2ec5edf3e63c
:END:

Use the timeclock keymap as noted in the timeclock source.

#+BEGIN_SRC emacs-lisp
(define-key ctl-x-map "ti" #'timeclock-in)
(define-key ctl-x-map "to" #'timeclock-out)
(define-key ctl-x-map "tc" #'timeclock-change)
(define-key ctl-x-map "tr" #'timeclock-reread-log)
(define-key ctl-x-map "tu" #'timeclock-update-mode-line)
(define-key ctl-x-map "tv" #'timeclock-visit-timelog)
(define-key ctl-x-map "tw" #'timeclock-when-to-leave-string)
(define-key ctl-x-map "tt" #'timeclock-mode-line-display)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq timeclock-file "/home/b/busi/archiv/timelogs/timelog")
#+END_SRC

** Diary
:PROPERTIES:
:ID:       862fc5d0-8951-491a-a6bb-9ca7ec8ef86a
:END:

Diary entries are useful sometimes.  E.g. it's possible to import ics
files into a diary.

Recall that in the org agenda the d key switches diary inclusion on or
off.

#+BEGIN_SRC emacs-lisp
;; for diary to include other diaries
(add-hook 'diary-list-entries-hook 'diary-include-other-diary-files)
(add-hook 'diary-mark-entries-hook 'diary-mark-included-diary-files)
#+END_SRC

** ERC
:PROPERTIES:
:ID:       4b406e7e-e0cf-43d9-9c1f-eac2db792324
:END:

Direct client-to-client support for erc.

#+BEGIN_SRC emacs-lisp
(eval-after-load "erc" '(require 'erc-dcc))
#+END_SRC

** Personal Emacs Settings
:PROPERTIES:
:ID:       e1e65f87-da4c-473c-86d7-34c120afbf7f
:END:

#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)

(ffap-bindings)
(global-set-key
 ""
 (lambda(&optional prefix)
   (interactive "P")
   (call-interactively
    (if prefix
        #'ido-find-file
      #'find-file-at-point))))

;; activate some page-related extensions
(require 'page-ext)
(define-key pages-directory-mode-map "q" 'quit-window) ; fixes hyperbole
;; (define-key pages-directory-mode-map "q" 'ignore)

(display-time)
#+END_SRC

** Zone
:PROPERTIES:
:ID:       99bb1105-bfd6-40d3-8f5d-caa68a14a8f3
:END:

zone is builtin.  I use zone as signal.

Set =zone-timeout= to a number to have zone stop after =zone-timeout=
seconds.

#+BEGIN_SRC emacs-lisp
(setq  zone-timeout 300)
#+END_SRC

** Emacs Lisp Hook
:PROPERTIES:
:ID:       5fc7403b-e78e-4f65-b0d7-247262e18269
:END:

#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook #'eldoc-mode)
(add-hook 'emacs-lisp-mode-hook #'imenu-add-menubar-index)
(add-hook 'emacs-lisp-mode-hook #'checkdoc-minor-mode)
#+END_SRC

** helm-bibtex
:PROPERTIES:
:ID:       b8f873fe-ddd5-4bb8-8700-ee97ca469db2
:END:

#+BEGIN_SRC emacs-lisp
(setq bibtex-completion-bibliography "/home/b/media/references/references.bib")
#+END_SRC

* Last line
:PROPERTIES:
:ID:       db249d39-55bb-4d29-9f4d-e088576236b7
:END:

#+begin_src emacs-lisp

;;; init:.el ends here
#+end_src


* Meta                                                             :noexport:

Local Variables:
eval: (git-auto-commit-mode)
End:
